texts = [
    "Hey, have you heard about this new ransomware variant that just surfaced? It's supposed to be really powerful.",
    "I've been studying the vulnerabilities in this company's network. I think we can exploit them and launch a ransomware attack.",
    "We've gained access to their system and planted the ransomware. Now we just have to wait for the right moment to activate it.",
    "I received an email from a potential victim. They seem clueless about ransomware attacks. Perfect target for us.",
    "The ransomware attack we launched last week was a huge success. They paid the ransom without hesitation.",
    "I've infiltrated their network and found sensitive files. I'm encrypting them now. This ransomware attack will cripple them.",
    "Our ransomware strain is spreading like wildfire. We've infected multiple organizations already.",
    "The victim tried to restore their files from a backup, but we encrypted those too. No escape from our ransomware.",
    "I'm about to send the ransom demand to the victim. Let's see how much they're willing to pay to regain control of their files.",
    "We've breached their defenses and gained admin access. The ransomware attack is imminent.",
    "The news just reported another ransomware attack on a major corporation. Looks like we're not the only ones in the game.",
    "Our team successfully encrypted their servers. It's time to let them know we have their data and demand a hefty ransom.",
    "I just received a payment confirmation from a victim. Looks like they value their data enough to pay the ransom.",
    "This ransomware strain is undetectable by most antivirus software. It's going to wreak havoc on their systems.",
    "We're seeing an increase in ransomware attacks targeting small businesses. They're an easy prey.",
    "The victim is begging for mercy and offering to pay the ransom. We hold all the power in this ransomware attack.",
    "I found a vulnerability in their network. It's the perfect entry point for our ransomware attack.",
    "The victim's files are fully encrypted. They have no choice but to pay up if they want to recover their data.",
    "Our ransomware is spreading through phishing emails. People just can't resist clicking on those malicious links.",
    "The ransomware attack is in progress. Their files are being encrypted one by one. They won't see it coming.",
    "We've gained control of their entire network. Now it's time to deploy the ransomware and maximize our profit.",
    "The victim tried to negotiate the ransom amount, but we're not budging. They should have protected their data better.",
    "I'm creating a custom ransom note for this attack. Gotta make it look convincing and strike fear into their hearts.",
    "The victim's IT team is clueless about dealing with ransomware. They have no idea how to stop us.",
    "We've encrypted their critical databases. Without the decryption key, their business will grind to a halt.",
    "The ransomware is spreading rapidly. We're hitting multiple targets simultaneously. It's chaos out there.",
    "I just received the ransom payment. Time to send them the decryption key and complete this successful attack.",
    "The victim fell for our ransomware trap. They clicked on an infected email attachment. Now they'll pay the price.",
    "This ransomware attack is a work of art. We've bypassed all their security measures and infiltrated their systems.",
    "I've been monitoring their network for weeks. We have all the information we need to execute the ransomware attack.",
    "The victim's panic is growing. They're realizing the severity of the ransomware attack. Pay up or lose everything.",
    "We're encrypting their customer database. Imagine the chaos when they realize all their sensitive data is gone.",
    "Our ransomware is demanding payment in cryptocurrency. It's untraceable, and the victim has no choice but to comply.",
    "I'm preparing the bitcoin wallet to receive the ransom payment. We'll make a fortune from this ransomware attack.",
    "The victim is desperately trying to recover their encrypted files. Little do they know, there's no going back.",
    "We're getting ready to unleash the ransomware on their network. It's going to be a devastating attack.",
    "The news is reporting a surge in ransomware attacks. Looks like the industry is booming.",
    "The victim's backups were outdated. They're completely helpless in the face of this ransomware attack.",
    "I'm leaving a signature in the victim's system. They'll know it was our group behind this ransomware attack.",
    "The ransom demand has been sent. Let's see how long it takes for the victim to pay up.",
    "We're encrypting their servers, file by file. Soon, their entire business will be at our mercy.",
    "The victim's network is under our control. They never stood a chance against our ransomware attack.",
    "I received a notification from the victim's system. They're starting to realize the extent of the ransomware attack.",
    "The encryption process is almost complete. This ransomware attack will leave them devastated.",
    "We're launching a massive ransomware campaign. No organization is safe from our reach.",
    "The victim's files are now encrypted with military-grade encryption. They won't crack it without our decryption key.",
    "I'm encrypting their database backups. They won't have a plan B to recover from this ransomware attack.",
    "The victim is reaching out to cybersecurity experts for help. Too little, too late. Our ransomware is unstoppable.",
    "We're targeting hospitals and healthcare providers with our ransomware. Lives are at stake, and they'll pay to save them.",
    "The victim is gathering the ransom payment. We hold their business in our hands.",
    "Our ransomware attack has paralyzed the victim's operations. They're losing money by the minute.",
    "I'm sending the victim a sample of their encrypted files. It's a warning of what's to come if they don't pay.",
    "The victim's network is infected with our ransomware. They're completely unaware of the ticking time bomb.",
    "We've breached their firewall and disabled their antivirus. It's time for the ransomware to take over.",
    "The victim's IT team is scrambling to contain the ransomware attack. It's a futile effort.",
    "I'm monitoring the victim's communication channels. They're considering paying the ransom. Smart move.",
    "The victim's employees are panicking. They can't access any of their files. Chaos is our ally in this ransomware attack.",
    "We've encrypted their email server. No communication, no chance of recovery. They'll have to pay.",
    "I'm encrypting their cloud storage. Their precious data will be locked away until they pay the ransom.",
    "The victim is desperately trying to negotiate a lower ransom amount. We're holding all the cards.",
    "Our ransomware has a built-in timer. If they don't pay within 72 hours, their files will be permanently deleted.",
    "I've gained root access to their servers. The ransomware attack is about to commence.",
    "The victim's CEO just realized the severity of the ransomware attack. They're in panic mode.",
    "We're encrypting their financial records. They won't be able to trace the money once they pay the ransom.",
    "I've set up a hidden backdoor in their system. Even if they remove the ransomware, we'll strike again.",
    "The victim's network is like a spiderweb. We're entangling them with our ransomware, trapping them in chaos.",
    "We're targeting government institutions with our ransomware. The stakes are high, and they'll pay a premium.",
    "I've gained control of their security cameras. They'll witness the havoc our ransomware unleashes.",
    "The victim is pleading with us to restore their files. But we have no intention of showing mercy.",
    "We're deploying the ransomware through a phishing campaign. The victims won't see it coming until it's too late.",
    "I've encrypted their backups. They won't find a way to recover their files without paying the ransom.",
    "The victim's network is crawling with our ransomware. It's a digital invasion they can't repel.",
    "We've infiltrated their network through a vulnerable third-party vendor. Their trust was their downfall.",
    "I received an email from a victim who thinks they can outsmart us. We'll prove them wrong with our ransomware.",
    "The victim's files are being held hostage. The clock is ticking, and the ransom is increasing every hour.",
    "We're demanding a substantial ransom amount. The victim's data is worth every penny.",
    "I've encrypted their research and development files. Our ransomware attack will set them back years.",
    "The victim is contemplating paying the ransom. It's a tough choice, but they have no other option.",
    "We've infected their network with ransomware. Their business is on the brink of collapse.",
    "I'm spreading the ransomware through malicious advertisements. They won't suspect a thing.",
    "The victim is frantically trying to find a decryption tool. They won't find one that can defeat our ransomware.",
    "We're attacking educational institutions with our ransomware. It's a goldmine of valuable data.",
    "I'm encrypting their customer information. It's a treasure trove for identity theft if they don't pay the ransom.",
    "The victim's security team is overwhelmed. They never anticipated a ransomware attack of this magnitude.",
    "We're targeting financial institutions. They'll pay a hefty ransom to protect their customers' data.",
    "I'm leaving a message on the victim's homepage. A reminder that their files are under our control.",
    "The victim's system is crawling with our ransomware. They're completely blind to our presence.",
    "We've encrypted their system backups. They won't find a way to restore their files without our decryption key.",
    "I'm encrypting their payroll system. They won't be able to pay their employees until they pay the ransom.",
    "The victim is begging us to lower the ransom amount. They're running out of time, and desperation is setting in.",
    "We're launching a coordinated ransomware attack on multiple targets. It's a synchronized chaos.",
    "I received an anonymous tip about a vulnerable system. It's the perfect target for our ransomware.",
    "The victim's executives are in a frenzy. They underestimated the impact of a ransomware attack.",
    "We're encrypting their intellectual property. They'll pay a high price to regain control of their valuable assets.",
    "I'm encrypting their communication channels. They're isolated, trapped with our ransomware.",
    "The victim's IT team is pleading with us for a decryption key. But we hold all the power in this ransomware attack.",
    "We're infiltrating their network through a compromised employee. They unknowingly became our gateway.",
    "I've encrypted their customer database. Their reputation is on the line if they don't pay the ransom.",
    "The victim is contemplating involving law enforcement. A futile attempt to stop our ransomware operation.",
    "We're encrypting their supply chain data. Their business operations will grind to a halt.",
    "I'm encrypting their critical infrastructure systems. They'll experience a digital apocalypse.",
    "The victim is searching for cybersecurity experts to negotiate on their behalf. It's a lost cause.",
    "We've infected their network with a polymorphic ransomware variant. It's constantly evolving, evading detection.",
    "I'm encrypting their server logs. They won't be able to trace our footsteps in this ransomware attack.",
    "The victim is desperately seeking a decryption tool. But they won't find one that can crack our encryption.",
    "We're targeting law firms with our ransomware. Their clients' confidential information is up for grabs.",
    "I've encrypted their backup servers. They're at our mercy with no chance of recovery without paying the ransom.",
    "The victim's security team is trying to identify the ransomware strain. They're playing catch-up, but it's futile.",
    "We're encrypting their research data. Years of hard work will go up in smoke if they don't meet our demands.",
    "I'm leaving a taunting message on the victim's screens. They'll know they're dealing with professional ransomware operators.",
    "The victim's system is paralyzed by our ransomware. They're living a nightmare they can't wake up from.",
    "We've encrypted their financial transactions. They won't be able to conduct business until they pay the ransom.",
    "I'm encrypting their server configurations. They'll struggle to restore their systems even if they pay the ransom.",
    "The victim's employees are spreading panic throughout the organization. Our ransomware thrives on chaos.",
    "We're demanding payment in bitcoin. It's the currency of choice for the dark side of the internet.",
    "I've encrypted their research prototypes. Our ransomware attack will set them back years in development.",
    "The victim is exploring legal avenues to recover their files. But the law can't protect them from our ransomware.",
    "We're targeting energy grids with our ransomware. The power is in our hands, quite literally.",
    "I'm encrypting their confidential emails. They won't be able to communicate without our decryption key.",
    "The victim is desperately contacting cybersecurity companies for assistance. None can save them from our ransomware.",
    "We've infiltrated their network through a vulnerable IoT device. They unwittingly invited us into their systems.",
    "I'm encrypting their customer transaction history. It's a valuable asset they can't afford to lose.",
    "The victim's network is collapsing under the weight of our ransomware. They're helpless against our digital onslaught.",
    "We're encrypting their logistics data. They won't be able to track shipments or manage inventory.",
    "I've encrypted their server certificates. They'll lose trust from their clients if they don't pay the ransom.",
    "The victim is contemplating shutting down their entire operation. They're realizing the magnitude of the ransomware attack.",
    "We've breached their cloud infrastructure. The ransomware attack will spread like wildfire through their virtual ecosystem.",
    "I'm encrypting their VPN connections. They'll be cut off from the outside world until they comply with our demands.",
    "The victim's management team is in disarray. They never prepared for a ransomware attack of this magnitude.",
    "We're targeting e-commerce platforms. Their customer data is a valuable asset for identity theft and fraud.",
    "I'm leaving a trail of breadcrumbs for the victim to follow. But it will only lead them deeper into our ransomware trap.",
    "The victim's system is compromised. Our ransomware lurks in the shadows, silently wreaking havoc.",
]

label = 'Ransomware Attacks'