forensic_keywords = [
    "weapon",
    "explosive",
    "drug",
    "money laundering",
    "fraud",
    "embezzlement",
    "forgery",
    "counterfeit",
    "cybercrime",
    "hacking",
    "data breach",
    "identity theft",
    "ransomware",
    "phishing",
    "malware",
    "steganography",
    "child exploitation",
    "human trafficking",
    "terrorism",
    "extortion",
    "blackmail",
    "insider trading",
    "insider threat",
    "money laundering",
    "organized crime",
    "corruption",
    "bribery",
    "narcotics",
    "firearm",
    "ammunition",
    "violent crime",
    "assault",
    "murder",
    "kidnapping",
    "sexual assault",
    "fraudulent activity",
    "financial crime",
    "money trail",
    "electronic evidence",
    "communication intercept",
    "covert operation",
    "surveillance",
    "forensic accounting",
    "forensic investigation",
    "chain of custody",
    "crime scene",
    "forensic analysis",
    "digital evidence",
    "computer forensics",
    "mobile forensics",
    "network forensics",
    "forensic imaging",
    "forensic tool",
    "forensic report",
    "forensic examination",
    "witness statement",
    "expert testimony"
]
