keyword_relations = {
    "weapon": ["firearm", "ammunition", "illegal", "possession", "trafficking", "arms", "gun", "knife", "weaponry", "firepower", "kill", "take out"],
    "explosive": ["bomb", "detonator", "explosives manufacturing", "explosives handling", "blasting", "incendiary", "ordnance", "pyrotechnic", "explosive device", "bombing"],
    "drug": ["narcotics", "controlled substance", "drug trafficking", "drug abuse", "substance abuse", "illicit drugs", "narcotic substances", "drug trade", "narcotic distribution", "drug deal", "drug cartel"],
    "money laundering": ["illicit funds", "financial crime", "money trail", "hidden assets", "illicit finance", "money transfer", "laundering operation", "money flow", "money scheme", "money mule"],
    "fraud": ["scam", "deception", "identity theft", "white-collar crime", "fraudulent scheme", "deceit", "swindle", "hoax", "fraudulent activity", "fraudulent transaction"],
    "embezzlement": ["misappropriation", "theft", "financial fraud", "corruption", "misuse of funds", "financial misconduct", "fraudulent appropriation", "embezzlement case", "embezzlement scheme"],
    "forgery": ["counterfeit", "document falsification", "signature forgery", "fraudulent documents", "fabrication", "counterfeiting", "imitation", "fraudulent replication", "forged signature", "forged document"],
    "counterfeit": ["fake", "replica", "imitation", "counterfeit currency", "fake money", "counterfeit goods", "forged", "phony", "counterfeit product", "counterfeit bill"],
    "cybercrime": ["cybersecurity", "data breach", "hacking", "malware", "cyber attack", "cyber fraud", "cyber theft", "cyber intrusion", "cybercrime investigation", "cybercrime prevention"],
    "hacking": ["cyber attack", "penetration testing", "network security", "vulnerability", "cyber intrusion", "cyber breach", "unauthorized access", "cyber espionage", "hacker", "hack into"],
    "data breach": ["cyber incident", "confidential data exposure", "data leak", "breach notification", "information breach", "data compromise", "data loss", "data theft", "breach investigation", "data breach response"],
    "identity theft": ["personal information theft", "identity fraud", "identity cloning", "stolen identity", "identity crime", "identity hijacking", "identity manipulation", "identity impersonation", "identity theft case", "identity theft victim"],
    "ransomware": ["malicious software", "crypto ransom", "data encryption", "cyber extortion", "ransom demand", "ransom attack", "ransom note", "ransom payment", "ransomware infection", "ransomware attack"],
    "phishing": ["fraudulent emails", "spoofing", "social engineering", "phishing scam", "phishing attack", "phishing website", "phishing email", "phishing link", "phishing campaign", "phishing attempt"],
    "terrorism": ["extremism", "radicalization", "terrorist organization", "violent acts", "terrorist activities", "terrorist threat", "terrorism financing", "counterterrorism", "terrorist attack", "terrorist plot"],
    "money smuggling": ["undeclared funds", "currency smuggling", "cash smuggling", "illegal money transfer", "cross-border smuggling", "money concealment", "smuggling operation", "smuggling route", "money smuggling case"],
    "child exploitation": ["child pornography", "online grooming", "child trafficking", "child abuse", "child sexual exploitation", "child exploitation material", "child exploitation network", "child exploitation investigation", "online child exploitation"],
    "corruption": ["bribery", "graft", "embezzlement", "abuse of power", "corrupt practices", "corruption scandal", "bribery scheme", "corruption network", "corruption investigation", "corruption allegation"],
    "organized crime": ["criminal syndicate", "mafia", "gang", "racketeering", "organized criminal activity", "crime syndicate", "gang activity", "criminal organization", "organized crime group", "organized crime network"],
    "kidnapping": ["abduction", "hostage-taking", "ransom", "criminal confinement", "kidnapping case", "kidnapping victim", "kidnapping plot", "kidnapping investigation", "kidnapping ransom", "kidnapping suspect"],
    "human trafficking": ["sex trafficking", "forced labor", "illegal immigration", "human smuggling", "trafficking ring", "human rights violation", "human trade", "human trafficking network", "human trafficking victim", "human trafficking investigation"],
    "cyber espionage": ["state-sponsored hacking", "cyber spying", "economic espionage", "nation-state actors", "cyber intelligence", "cyber warfare", "espionage campaign", "cyber espionage group", "cyber espionage operation"],
    "arson": ["fire", "incendiary", "fire investigation", "arsonist", "fire damage", "arson case", "arson evidence", "arson investigation", "intentional fire", "arson suspect"],
    "fraudulent bankruptcy": ["bankruptcy fraud", "insolvency fraud", "false bankruptcy claim", "concealing assets", "fraudulent bankruptcy scheme", "bankruptcy investigation", "bankruptcy crime", "bankruptcy fraud case"],
    "terrorism financing": ["funding terrorism", "money laundering", "terrorist financing network", "illicit funds", "terrorist financial support", "terrorism financing investigation", "terrorist financing methods", "terrorist financing activity"],
    "public corruption": ["government corruption", "official misconduct", "abuse of public office", "bribery of public official", "corruption in public sector", "public corruption investigation", "public corruption case", "corrupt government official"],
    "human smuggling": ["illegal immigration", "border crossing", "human trafficking", "illegal transportation", "human smuggling network", "smuggling routes", "human smuggling operation", "human smuggling investigation"],
    "money counterfeiting": ["counterfeit currency", "counterfeit money production", "counterfeit detection", "counterfeit note", "counterfeit money circulation", "counterfeit money investigation", "counterfeit money ring", "counterfeit money case"],
    "child pornography": ["child exploitation material", "child sexual abuse material", "child pornography production", "child pornography distribution", "child pornography possession", "child pornography investigation", "child pornography ring", "online child exploitation"],
    "cyberbullying": ["online harassment", "cyber harassment", "cyber threats", "cyberstalking", "online intimidation", "cyberbullying prevention", "cyberbullying investigation", "cyberbullying case"],
    "money seizure": ["asset forfeiture", "cash seizure", "illegal funds confiscation", "money confiscation", "proceeds of crime", "money seizure operation", "money seizure investigation", "seized funds"],
    "cyber intrusion": ["data breach", "network breach", "unauthorized access", "cyber attack", "intrusion detection", "cyber intrusion prevention", "cyber intrusion investigation", "cyber intrusion response"],
    "evidence tampering": ["manipulation of evidence", "destruction of evidence", "concealment of evidence", "fabrication of evidence", "evidence tampering investigation", "evidence tampering case", "obstruction of justice"],
    "money mule": ["money laundering", "illicit funds transfer", "money transfer agent", "money laundering operation", "money mule recruitment", "money mule network", "money mule investigation", "money mule case"],
    "forensic entomology": ["insect evidence", "insect infestation", "forensic entomologist", "insect colonization", "postmortem interval", "insect activity", "entomological evidence", "insect succession"],
    "forensic anthropology": ["skeletal remains", "human identification", "forensic osteology", "anthropological analysis", "forensic archaeology", "skeletal trauma", "bone analysis", "human skeletal remains"],
    "forensic odontology": ["dental records", "bite mark analysis", "forensic dental identification", "forensic bite mark analysis", "dental impression", "dental identification", "forensic dental examination", "dental forensic expert"],
    "forensic toxicology": ["poisoning", "drug analysis", "alcohol testing", "toxicology report", "postmortem toxicology", "drug overdose", "toxicological analysis", "forensic toxicologist"]
}

keyword_relations1 = {
    "weapon": ["firearm", "ammunition", "illegal", "possession", "trafficking", "arms", "gun", "knife", "weaponry", "firepower"],
    "explosive": ["bomb", "detonator", "explosives manufacturing", "explosives handling", "blasting", "incendiary", "ordnance", "pyrotechnic"],
    "drug": ["narcotics", "controlled substance", "drug trafficking", "drug abuse", "substance abuse", "illicit drugs", "narcotic substances", "drug trade", "narcotic distribution"],
    "money laundering": ["illicit funds", "financial crime", "money trail", "hidden assets", "illicit finance", "money transfer", "laundering operation", "money flow"],
    "fraud": ["scam", "deception", "identity theft", "white-collar crime", "fraudulent scheme", "deceit", "swindle", "hoax"],
    "embezzlement": ["misappropriation", "theft", "financial fraud", "corruption", "misuse of funds", "financial misconduct", "fraudulent appropriation"],
    "forgery": ["counterfeit", "document falsification", "signature forgery", "fraudulent documents", "fabrication", "counterfeiting", "imitation", "fraudulent replication"],
    "counterfeit": ["fake", "replica", "imitation", "counterfeit currency", "fake money", "counterfeit goods", "forged", "phony"],
    "cybercrime": ["cybersecurity", "data breach", "hacking", "malware", "cyber attack", "cyber fraud", "cyber theft", "cyber intrusion"],
    "hacking": ["cyber attack", "penetration testing", "network security", "vulnerability", "cyber intrusion", "cyber breach", "unauthorized access", "cyber espionage"],
    "data breach": ["cyber incident", "confidential data exposure", "data leak", "breach notification", "information breach", "data compromise", "data loss", "data theft"],
    "identity theft": ["personal information theft", "identity fraud", "identity cloning", "stolen identity", "identity crime", "identity hijacking", "identity manipulation", "identity impersonation"],
    "ransomware": ["malicious software", "crypto ransom", "data encryption", "cyber extortion", "ransom demand", "ransom attack", "ransom note", "ransom payment"],
    "phishing": ["fraudulent emails", "spoofing", "social engineering", "phishing scam", "phishing attack", "phishing website", "phishing email", "phishing link"],
    "malware": ["computer virus", "trojan", "worm", "malicious code", "malicious software", "cyber infection", "virus attack", "malware distribution"],
    "steganography": ["hidden messages", "covert communication", "image manipulation", "concealed data", "steganographic techniques", "secret communication", "invisible data", "covert encoding"],
    "child exploitation": ["child pornography", "online grooming", "sexual abuse", "child trafficking", "child exploitation material", "child endangerment", "child victimization", "child exploitation network"],
    "human trafficking": ["modern slavery", "forced labor", "sex trafficking", "illegal immigration", "human smuggling", "trafficking ring", "human rights violation", "human trade"],
    "terrorism": ["extremism", "radicalization", "terrorist organization", "violent acts", "terrorist activities", "terrorist threat", "terrorism financing", "counterterrorism"],
    "extortion": ["blackmail", "coercion", "threats", "demand for money", "extortion scheme", "blackmail letter", "extortion payment", "coercive tactics"],
    "blackmail": ["extortion", "threats", "compromising information", "demand for secrecy", "blackmail scheme", "blackmail victim", "blackmail evidence", "blackmail negotiation"],
    "insider trading": ["securities fraud", "insider information", "stock market manipulation", "illegal trading", "insider dealing", "insider information leak", "stock fraud", "insider trading scheme"],
    "insider threat": ["insider sabotage", "unauthorized access", "data theft", "internal security breach", "insider attack", "insider risk", "employee misconduct", "insider vulnerability"],
    "money laundering": ["illicit funds", "financial crime", "money trail", "hidden assets", "illicit finance", "money transfer", "laundering operation", "money flow"],
    "organized crime": ["criminal syndicate", "mafia", "gang", "racketeering", "organized criminal activity", "crime syndicate", "gang activity", "criminal organization"],
    "corruption": ["bribery", "graft", "embezzlement", "abuse of power", "corrupt practices", "corruption scandal", "bribery scheme", "corruption network"],
    "bribery": ["corruption", "graft", "kickback", "bribe", "bribery attempt", "bribery case", "bribery investigation", "bribery allegation"],
    "narcotics": ["drug", "illegal substances", "controlled substance", "drug trafficking", "narcotic substances", "drug trade", "drug smuggling", "drug abuse"],
    "firearm": ["weapon", "gun", "ammunition", "gun violence", "kill", "take out", "firearm possession", "illegal firearm", "firearm trafficking"],
    "ammunition": ["weapon", "firearm", "bullet", "gunpowder", "ammunition stockpile", "ammunition sale", "illegal ammunition", "ammunition possession"],
    "violent crime": ["assault", "murder", "robbery", "aggravated assault", "violent behavior", "violent act", "violent incident", "violent offender"],
    "assault": ["violent crime", "physical attack", "battery", "domestic violence", "assault and battery", "assault charge", "assault victim", "assault case"],
    "murder": ["homicide", "manslaughter", "crime scene", "forensic investigation", "kill", "take out", "murder case", "murder suspect", "murder weapon"],
    "kidnapping": ["abduction", "hostage-taking", "ransom", "criminal confinement", "kidnapping case", "kidnapping victim", "kidnapping plot", "kidnapping investigation"],
    "sexual assault": ["rape", "sexual violence", "sexual harassment", "victim", "sexual assault case", "sexual assault survivor", "sexual assault allegation", "sexual assault report"],
    "fraudulent activity": ["scam", "deception", "financial fraud", "fraudulent transactions", "fraudulent scheme", "fraudulent behavior", "fraudulent operation", "fraudulent activity detection"],
    "financial crime": ["fraud", "money laundering", "embezzlement", "corruption", "financial misconduct", "financial fraud investigation", "financial crime prevention", "financial crime detection"],
    "money trail": ["financial transactions", "paper trail", "financial records", "money flow", "financial investigation", "money transfer trail", "money transaction history", "money movement analysis"],
    "electronic evidence": ["digital evidence", "computer records", "communication data", "electronic devices", "electronic data analysis", "digital evidence collection", "computer forensics", "digital device examination"],
    "communication intercept": ["wiretap", "eavesdropping", "surveillance", "interception", "communication monitoring", "intercepted messages", "surveillance operation", "wiretapping investigation"],
    "covert operation": ["undercover mission", "clandestine activity", "secret operation", "intelligence gathering", "covert investigation", "clandestine operation", "undercover agent", "covert surveillance"],
    "surveillance": ["monitoring", "tracking", "observation", "intelligence gathering", "surveillance cameras", "surveillance footage", "surveillance operation", "surveillance techniques"],
    "forensic accounting": ["financial investigation", "audit trail", "financial analysis", "money tracing", "forensic audit", "financial fraud examination", "accounting irregularities", "fraudulent transactions analysis"],
    "forensic investigation": ["crime scene", "evidence collection", "analysis techniques", "forensic examination", "forensic analysis", "crime scene reconstruction", "forensic evidence", "investigation procedures"],
    "chain of custody": ["evidence integrity", "handling procedures", "documentation", "evidence tracking", "evidence chain", "chain of custody form", "evidence custody process", "evidence documentation"],
    "crime scene": ["forensic investigation", "evidence collection", "crime scene analysis", "forensic techniques", "crime scene examination", "crime scene reconstruction", "crime scene evidence", "crime scene processing"],
    "forensic analysis": ["examination", "scientific analysis", "forensic techniques", "interpretation", "forensic examination", "forensic science", "forensic testing", "forensic comparison"],
    "digital evidence": ["electronic data", "computer records", "digital artifacts", "forensic analysis", "digital forensics", "digital crime evidence", "digital device data", "forensic data recovery"],
    "computer forensics": ["digital forensics", "data recovery", "cyber investigation", "forensic techniques", "computer forensic analysis", "computer evidence examination", "computer crime investigation", "digital device forensics"],
    "mobile forensics": ["cell phone analysis", "mobile device examination", "data extraction", "forensic tools", "mobile forensic investigation", "cell phone forensics", "mobile device data recovery", "mobile device evidence"],
    "network forensics": ["network traffic analysis", "intrusion detection", "incident response", "packet capture", "network forensic investigation", "network intrusion analysis", "network security incident", "network traffic monitoring"],
    "forensic imaging": ["disk cloning", "bitstream copy", "data preservation", "forensic duplication", "forensic data imaging", "disk imaging process", "forensic data preservation", "forensic disk duplication"],
    "forensic tool": ["software", "hardware", "forensic software", "investigation utilities", "forensic toolset", "digital forensic tools", "computer forensic software", "forensic hardware devices"],
    "forensic report": ["findings", "conclusions", "expert opinion", "analysis results", "forensic analysis report", "forensic examination findings", "expert witness report", "forensic report writing"],
    "forensic examination": ["investigation process", "analysis techniques", "evidence review", "scientific methods", "forensic analysis", "forensic examination procedures", "evidence examination process", "forensic testing"],
    "witness statement": ["testimony", "eyewitness account", "deposition", "oral evidence", "witness testimony", "witness interview", "eyewitness statement", "witness deposition"],
    "expert testimony": ["forensic expert", "court witness", "qualified opinion", "legal testimony", "expert witness", "forensic expert testimony", "expert testimony admissibility", "expert opinion in court"]
}

keywords_combines = {**keyword_relations, **keyword_relations1}

keywords = []
for key, values in keywords_combines.items():
    keywords.append(key)
    keywords.extend(values)
    
if __name__ == "__main__":    
    import json
    json_data = json.dumps(keywords, indent=4)
    with open("keywords.json", "w") as json_file:
        json_file.write(json_data)