data = {
    "forensics": {
        "texts": [
            # Incident Types
            "Unauthorized access attempt detected from IP address 123.456.789.0",
            "Data breach reported in company database.",
            "Email phishing scam targeting employees.",
            # Communication Types
            "Chat conversation related to the case.",
            "Email exchange discussing sensitive information.",
            "Social media post indicating potential cyberbullying.",
            # User Activities
            "File deletion activity on suspect's computer.",
            "Suspicious browsing history found on the device.",
            "Evidence of encrypted files on external storage device.",
            # Data Categories
            "Disclosure of personal identifiable information (PII).",
            "Financial records found on suspect's computer.",
            "Discovery of confidential business documents on an unauthorized device.",
            # Attack Techniques
            "Malware detected in the system.",
            "Evidence of SQL injection attack in the web server logs.",
            "Brute-force login attempts on the network server.",
            # Investigation Steps
            "Digital evidence collection and preservation process.",
            "Forensic analysis of hard drive for deleted files.",
            "Documentation and reporting of forensic findings.",
        ],
        "labels": [
            # Incident Types
            "Threat",
            "Security Breach",
            "Phishing",
            # Communication Types
            "Communication",
            "Communication",
            "Cyberbullying",
            # User Activities
            "Data Manipulation",
            "Internet Activity",
            "Data Encryption",
            # Data Categories
            "PII Exposure",
            "Financial Data",
            "Trade Secret Breach",
            # Attack Techniques
            "Malware Attack",
            "SQL Injection",
            "Brute-force Attack",
            # Investigation Steps
            "Evidence Collection",
            "Digital Forensic Analysis",
            "Reporting and Documentation",
        ],
    },
    "sentiment": {
        "texts": [
            "I absolutely loved the movie! The acting was superb and the story was captivating.",
            "The food at that restaurant was terrible. I would not recommend it to anyone.",
            "It was an average experience. Nothing exceptional, but not bad either.",
            "The new album is fantastic! The artist did an amazing job.",
            "I was extremely disappointed with the customer service. It was rude and unhelpful.",
            "The weather today is neither good nor bad. It's just average.",
            "The team played exceptionally well and won the championship!",
            "The company's decision to lay off employees was disheartening and poorly executed.",
            "The book was okay. It didn't impress me much, but it was not terrible either.",
            "The concert was phenomenal! The energy and performance were outstanding.",
            "I love this product!",
            "The movie was amazing.",
            "The restaurant had terrible service.",
            "The concert was disappointing.",
            "I'm not sure how I feel about this book.",
            "The customer support was exceptional.",
            "The weather is beautiful today.",
            "This car is a disappointment.",
            "The hotel exceeded my expectations.",
            "I can't stand this place.",
            "I absolutely loved the movie! The acting was superb and the story was captivating.",
            "The food at that restaurant was terrible. I would not recommend it to anyone.",
            "It was an average experience. Nothing exceptional, but not bad either.",
            "The new album is fantastic! The artist did an amazing job.",
            "I was extremely disappointed with the customer service. It was rude and unhelpful.",
            "The weather today is neither good nor bad. It's just average.",
            "The team played exceptionally well and won the championship!",
            "The company's decision to lay off employees was disheartening and poorly executed.",
            "The book was okay. It didn't impress me much, but it was not terrible either.",
            "The concert was phenomenal! The energy and performance were outstanding.",
            "I had a wonderful time at the party. The atmosphere was great, and everyone was friendly.",
            "The hotel room was dirty and poorly maintained. I had a terrible experience.",
            "The customer support was prompt and helpful. They resolved my issue quickly.",
            "The movie was predictable and lacked originality. I expected more from it.",
            "The product is of high quality. It's worth every penny.",
            "The traffic was unbearable today. It took me hours to reach my destination.",
            "The staff at the store was courteous and went above and beyond to assist me.",
            "The play was mediocre. The acting was subpar, and the plot was confusing.",
            "The smartphone is sleek and packed with features. I'm impressed with its performance.",
            "The flight was delayed, and the airline provided no clear updates. It was frustrating.",
            "The coffee shop has a cozy ambiance, and their coffee is delicious. I highly recommend it.",
            "The movie was a masterpiece. The acting, direction, and storyline were all exceptional.",
            "I had a horrible experience at the restaurant. The food was cold, and the service was slow.",
            "The product exceeded my expectations. It is well-designed and functions flawlessly.",
            "The concert was electrifying. The energy of the crowd and the performance of the band were incredible.",
            "I was deeply unsatisfied with the customer support. They were unresponsive and unhelpful.",
            "The weather is absolutely beautiful today. It's perfect for outdoor activities.",
            "The team put up a commendable performance, although they didn't win the championship.",
            "The company's decision to cut costs by laying off employees was disappointing and unfair.",
            "The book was captivating from start to finish. The writing style and plot kept me engaged.",
            "The concert was a complete disaster. The sound quality was poor, and there were technical issues.",
            "I had an amazing time at the party. The decorations, music, and company were all fantastic.",
            "The hotel had terrible amenities and the rooms were dirty. I would not recommend staying there.",
            "The customer support was friendly and went above and beyond to solve my issue. Great service!",
            "The movie was clichéd and lacked originality. It was a disappointment.",
            "The product is of poor quality. It broke within a week of purchase.",
            "The traffic was minimal today. I reached my destination in record time.",
            "The staff at the store was unhelpful and seemed disinterested in assisting customers.",
            "The play was outstanding. The performances were stellar, and the script was thought-provoking.",
            "The smartphone is overpriced for its features. There are better alternatives available.",
            "The flight was delayed, but the airline provided clear updates and handled the situation well.",
            "The coffee shop has a cozy atmosphere, and their coffee is excellent. It's my favorite spot.",
        ],
        "labels": [
            "Positive",
            "Negative",
            "Neutral",
            "Positive",
            "Negative",
            "Neutral",
            "Positive",
            "Negative",
            "Neutral",
            "Positive",
            "Positive",
            "Positive",
            "Negative",
            "Negative",
            "Neutral",
            "Positive",
            "Positive",
            "Negative",
            "Positive",
            "Negative",
            "Positive",
            "Negative",
            "Neutral",
            "Positive",
            "Negative",
            "Neutral",
            "Positive",
            "Negative",
            "Neutral",
            "Positive",
            "Positive",
            "Negative",
            "Positive",
            "Negative",
            "Positive",
            "Negative",
            "Positive",
            "Negative",
            "Positive",
            "Negative",
            "Positive",
            "Negative",
            "Positive",
            "Positive",
            "Negative",
            "Positive",
            "Neutral",
            "Negative",
            "Positive",
            "Negative",
            "Positive",
            "Negative",
            "Positive",
            "Negative",
            "Negative",
            "Positive",
            "Negative",
            "Positive",
            "Negative",
            "Negative",
            "Positive",
        ],
    },
}
