texts = [
    "Yo, man! I just got a fresh batch of the good stuff. Gotta make sure our communication with the suppliers is tight. We don't want the pigs sniffing around.",
    "Listen up, guys. There's a new smuggling route we gotta explore. It's risky, but if we play our cards right, we can move massive amounts of product undetected.",
    "Everything went smooth with the last transaction. The goods were shipped discreetly, and the buyers got what they paid for. No hiccups, no heat.",
    "He's claiming to have connections to the big shots in the drug game. We gotta keep our heads down and talk in code. Can't afford any slip-ups.",
    "The narcs are on a rampage, man. They're busting drug operations left and right. We gotta be extra careful and change up our communication tactics to stay off their radar.",
    "Hey, listen, I got a lead on a new supplier. They're legit and have some top-grade product. We gotta make contact and set up a meet ASAP.",
    "I heard from a buddy that there's a big shipment coming in. We need to get our hands on it before someone else does. Gotta make the right calls to secure our share.",
    "We're running low on inventory. It's time to reach out to the suppliers and stock up. We can't afford to have empty shelves, you know what I'm saying?",
    "That last deal was a close call, man. We narrowly escaped getting caught. We gotta tighten up our security and make sure our suppliers are trustworthy.",
    "I met this dude at a party who knows a guy that can hook us up with a new product line. We should hit him up and see what he's got in store for us.",
    "The competition is getting fierce. We need to up our game and find better suppliers. The ones we got now ain't cutting it anymore.",
    "I've been hearing rumors about a snitch in our crew. We need to be extra cautious and change our communication methods. We can't risk any leaks.",
    "I just got a tip about a secret stash house where they keep a ton of drugs. We gotta figure out how to get in there and grab what we can without getting caught.",
    "We need to diversify our supply chain, man. Relying on just one source is dangerous. Let's start scouting for new suppliers and open up more options.",
    "I saw some suspicious activity near our operation. We might have a rat among us. We gotta tighten security and find out who's been blabbing to the cops.",
    "You know that guy we've been dealing with? Turns out he's been skimming off the top. We can't let him get away with it. Gotta teach him a lesson.",
    "I need a new burner phone for secure communication. This one's been compromised. We can't afford any wiretaps or surveillance.",
    "We gotta lay low for a while. The heat is intense right now, and we don't want any unnecessary attention. No flashy moves, got it?",
    "I just found out our main supplier got busted. We're in trouble if we don't find a replacement soon. Time to make some calls and find a new connect.",
    "I've been working on a foolproof plan to transport drugs across the border. It involves a hidden compartment in a truck. We should discuss the details.",
    "The boss wants us to expand our territory. We gotta make contacts in neighboring cities and set up distribution networks. It's time to grow, baby!",
    "I've been hearing whispers about a rival crew planning to take us down. We need to step up our security and keep an eye on anyone acting suspicious.",
    "Our current communication methods are outdated. We need to embrace encryption and secure apps to stay ahead of the game. Can't let the feds intercept our messages.",
    "I got a guy who knows a guy who can get us some heavy artillery. We might need it to protect our turf. Let's meet up and discuss the details.",
    "Remember that stash we buried in the woods? Someone must have dug it up. We gotta find out who's been snooping around and deal with them accordingly.",
    "I got a tip that the cops are onto our operation. We gotta shut it down temporarily and lay low until things cool off. Safety first, fellas.",
    "We need to establish a secure drop-off point for our suppliers. Somewhere discreet where they can leave the goods without raising suspicion.",
    "I've been studying the patterns of the local police. We can exploit their blind spots and carry out our operations without them noticing. It's all about timing.",
    "The demand for our product is skyrocketing. We gotta find a way to meet the increased orders without attracting too much attention. Time to scale up.",
    "Our last shipment got seized at the port. Someone must have tipped off the authorities. We need to investigate and find the leak in our organization.",
    "I'm meeting our supplier tomorrow to negotiate better prices. Gonna use my charm and persuasive skills to get us a sweet deal. Wish me luck!",
    "The streets are getting flooded with low-quality stuff. We gotta maintain our reputation for top-notch product. Quality control is key, guys.",
    "I heard a rumor about a new super potent drug hitting the market. We should get our hands on it and become the go-to source for the good stuff.",
    "We need to keep a close eye on our rivals. They're getting bolder by the day. Let's gather intel and be ready to strike if they cross the line.",
    "I just got an encrypted message from our supplier. He wants to meet up in person to discuss some sensitive matters. Should we go?",
    "The supplier is insisting on using a new code phrase for our transactions. It's a precautionary measure to avoid detection. We gotta adapt and learn it.",
    "Our operation is growing, but so is the risk. We need to set up a system to vet our new recruits and make sure we don't let any undercover agents in.",
    "I've been reading about a new technology that can hide drugs in everyday objects. We should explore that option to avoid suspicion during transport.",
    "The supplier messed up the last order. We gotta confront him and make sure he understands the consequences of his mistakes. Can't afford any more slip-ups.",
    "I just got a tip about a major drug bust the cops are planning. We need to change our routes and lie low until they execute their operation.",
    "Our main supplier wants us to expand our distribution network. It's a risky move, but the reward is worth it. We gotta think big and make it happen.",
    "I've been thinking about setting up a front business to launder our money. It's time to legitimize our operation and fly under the radar.",
    "We gotta tighten our security at the stash house. Install surveillance cameras, reinforce the doors. We can't let anyone break in and steal our product.",
    "I met this hacker who claims he can erase our digital footprints. We should bring him on board to protect our online activities from prying eyes.",
    "The supplier just gave me a heads-up about a new law enforcement operation in the area. We need to go underground and minimize our activities for a while.",
    "I don't trust our current courier. He's been acting shady lately. We should find a more reliable person to handle the transportation of our goods.",
    "I just got intel on a rival gang's hideout. We should hit them hard and seize their territory. It's time to show them who's boss.",
    "Our suppliers are demanding higher prices due to increased risks. We gotta negotiate with them and find a way to keep our costs in check.",
    "I spotted an undercover cop snooping around our operation. We need to set up a trap and expose him before he gathers enough evidence.",
    "I've been reading about this new encrypted messaging app. It's supposedly unhackable. We should switch to it for our sensitive communications.",
    "The boss is paranoid about wiretaps. We need to conduct all our meetings in secure locations and use white noise generators to mask our voices.",
    "Our rivals are spreading rumors about our product being low quality. We gotta show them who's got the real deal. Let's organize a blind taste test.",
    "I just received a message from our supplier. He wants us to start testing a new type of synthetic drug. We gotta be cautious and check it out before committing.",
    "Our suppliers are getting sloppy. They're delivering the goods late and causing us losses. It's time to have a serious talk and straighten things out.",
    "I've been hearing about a snitch in our crew. We need to find out who it is and make an example out of them. Can't let traitors ruin everything we built.",
    "We should set up a backup communication system in case our main one gets compromised. Gotta stay connected even when the heat is on.",
    "I just got a tip about a corrupt cop who's been taking bribes from other drug gangs. We should expose him and use it to our advantage.",
    "Our supplier wants to meet face-to-face to discuss a new batch. We should go, but let's take extra precautions and do a thorough security check first.",
    "I heard about a secret underground lab where they're cooking up a new type of hallucinogenic drug. We should try to get our hands on the recipe.",
    "Our buyers are demanding faster delivery. We gotta optimize our distribution process and find ways to minimize the time it takes to get the product to them.",
    "I got a new contact who can provide us with high-quality counterfeit bills. We should diversify our income streams and get into the money game too.",
    "We need to upgrade our surveillance equipment. The old cameras are grainy and unreliable. We gotta see everything that's happening around our operation.",
    "The supplier wants to change the drop-off location for our shipments. We gotta adapt to the new plan and ensure smooth transactions.",
    "I've been hearing rumors about a rival gang moving into our territory. We can't let them take over. It's time to rally our crew and show them who's in charge.",
    "We need to educate our runners about the risks involved in drug trafficking. Let's organize a training session and teach them how to stay safe and avoid detection.",
    "I just received a call from an anonymous source warning us about an upcoming raid. We need to gather our assets and relocate our stash immediately.",
    "Our suppliers are pushing a new synthetic drug. We should test it out and see if it's worth adding to our inventory. Gotta stay ahead of the trends.",
    "I've been studying the habits of the local cops. We need to exploit their weaknesses and find ways to outsmart them. It's a cat-and-mouse game, my friends.",
    "We need to find a way to transport drugs across the border without arousing suspicion. Maybe we can use a network of mules or hide the drugs in unconventional places.",
    "I just received a text from an unknown number. They claim to have valuable information about a rival gang. Should we meet up and hear them out?",
    "Our supplier wants us to start pushing a new party drug that's gaining popularity. We should tap into that market and make some serious cash.",
    "I bumped into a guy who used to work for our rivals. He's willing to spill their secrets in exchange for protection. We should bring him into our circle.",
    "The authorities are cracking down on drug trafficking in the city. We need to keep a low profile and avoid unnecessary risks. Lay low and play it safe.",
    "Our stash house got raided last night. We suspect an inside job. We gotta find the traitor and make sure they pay for betraying us.",
    "I got word that a rival gang is planning an ambush. We need to beef up our security and be prepared for a surprise attack.",
    "Our supplier wants us to switch to a more potent strain of marijuana. The customers are demanding it. We gotta keep up with the trends.",
    "I just found out that our supplier has been skimming profits. We can't let him get away with it. We gotta confront him and set things straight.",
    "Our encrypted communication channel got compromised. We need to create a new one and inform all the key players about the change.",
    "The cops are getting more sophisticated in their surveillance techniques. We gotta invest in counter-surveillance equipment to stay one step ahead.",
    "I heard rumors about a snitch in the police department leaking information to drug gangs. We should find a way to exploit that source and gain an edge.",
    "Our main supplier is getting greedy. He's jacking up the prices. We need to find alternatives and negotiate better deals. Can't let him take us for a ride.",
    "I just received a tip about a potential rival gang member infiltrating our crew. We gotta be extra cautious and test everyone's loyalty.",
    "We should invest in a safe house where we can store our drugs and hold meetings. Somewhere off the grid where the cops won't suspect a thing.",
    "The boss wants us to establish connections with corrupt officials. It'll give us protection and inside information. Time to grease some palms.",
    "I heard about a new drug detection technology the cops are using. We gotta figure out how to beat it and ensure our product goes undetected.",
    "Our supplier wants us to expand our market to the neighboring city. It's a risky move, but the potential profits are huge. Let's make it happen.",
    "I've been working on a plan to bribe a key informant in the police department. With their help, we can eliminate a major obstacle. Money talks, my friends.",
    "Our suppliers are demanding advance payments now. We need to gather enough cash to keep the supply chain flowing smoothly. Time to count our stacks.",
    "I just heard about a secret underground network that can help us transport drugs internationally. We should explore that option and expand our reach.",
    "Our runner got caught by the cops. We need to bail him out and make sure he doesn't spill any information. Loyalty is everything in this game.",
    "I got a lead on a corrupt customs officer. With their help, we can smuggle drugs through the ports without arousing suspicion. It's time to make a deal.",
    "Our rivals are getting desperate. They're stealing our customers and encroaching on our territory. We need to teach them a lesson they won't forget.",
    "I just got intel on a new drug recipe that's making waves in the market. We should acquire the formula and start producing it ourselves. Cut out the middleman.",
    "Our supplier wants to introduce a new distribution method using drones. It's risky, but it could revolutionize our operation. We should give it a shot.",
    "I bumped into an old friend who's now a cop. He's willing to turn a blind eye to our activities in exchange for a cut. Should we trust him?",
    "Our runners are getting sloppy. We need to train them better and emphasize the importance of discretion and attention to detail.",
    "I just heard about a rival gang member who wants to defect and join our ranks. We should meet up with him and see if he's worth the risk.",
    "The police have set up surveillance cameras in our neighborhood. We need to identify their blind spots and find ways to avoid detection.",
    "Our supplier wants us to switch to a new smuggling route through the mountains. It's treacherous, but the security checkpoints are less stringent.",
    "I've been studying the habits of the local police chief. We should gather compromising information on him and use it as leverage if needed.",
    "We need to establish a network of informants in the law enforcement agencies. With their help, we can stay one step ahead of the game.",
    "I just received a tip about a rival gang's safe house. We should hit it tonight and seize their drugs. Let's show them we mean business.",
    "Our supplier wants us to start using a private jet for transport. It's expensive, but it'll minimize the risk of interception. We gotta fly high and under the radar.",
    "I met a guy who specializes in forging documents. We should hire him to create fake identities and cover our tracks. Can't leave any trace behind.",
    "The cops are onto our money laundering operation. We need to move the funds to offshore accounts and cover our tracks. It's time to play hide and seek.",
    "Our main supplier wants us to distribute drugs to high-profile clients. It's risky, but the rewards are immense. We gotta cater to the elite.",
    "I just received a message from a rival gang leader. He wants to meet and negotiate a truce. Should we trust him or prepare for war?",
    "Our current stash house is compromised. We need to find a new location and transfer the drugs without attracting any attention.",
    "I've been hearing rumors about a corrupt judge who can tip the scales in our favor. We should make contact and see if we can strike a deal.",
    "Our courier got arrested with a small quantity of drugs. We need to bail him out and tighten our security protocols. No more slip-ups.",
    "I just received a call from a contact in the police department. He's willing to share confidential information in exchange for a cut. Should we take the risk?",
    "Our suppliers are pressuring us to increase the quantity of drugs we order. We need to find a way to meet their demands without raising suspicion.",
    "I heard about a new drug-sniffing dog the police are using. We should train our runners to evade them and outsmart their noses.",
    "Our rivals are trying to recruit our runners. We need to boost morale and show them why loyalty to us is worth more than a few extra bucks.",
    "I just got a tip about an upcoming police raid on one of our distribution points. We need to evacuate the area and relocate the goods immediately.",
    "Our supplier wants us to start using coded messages in our communications. It'll add an extra layer of security. Time to brush up on our cryptography skills.",
    "I bumped into a journalist who's been sniffing around our operation. We should find a way to silence him and protect our secrets. Loose lips sink ships.",
    "The authorities are tightening the noose on drug trafficking. We need to adapt and find innovative ways to move our product. Innovation is the key to survival.",
    "Our runner got jumped by a rival gang. We need to retaliate and send them a message. Nobody messes with our crew and gets away with it.",
    "I just received a call from an anonymous tip line. They're threatening to expose our operation unless we pay them off. We gotta track them down and shut them up.",
    "Our supplier wants us to start producing counterfeit prescription drugs. It's a lucrative market, but it comes with heightened scrutiny. We gotta tread carefully.",
    "I heard about a corrupt politician who's been protecting drug gangs in exchange for bribes. We should leverage that connection and secure our operations.",
    "Our distributors are getting sloppy. They're getting caught with large sums of cash. We need to train them in money laundering techniques and keep them under the radar.",
    "I just received a message from an old friend who's now a police informant. He's willing to feed us information in exchange for protection. Should we take him in?",
    "Our supplier wants us to start using encrypted USB drives for communication. We gotta stay ahead of the technological curve and keep our messages secure.",
    "I've been hearing rumors about a new synthetic drug that's causing a frenzy in the underground scene. We should get our hands on it and corner the market.",
    "We need to establish connections with local gang leaders. Their protection can ward off rival gangs and ensure our operations run smoothly.",
    "I just spotted an undercover cop staking out our stash house. We need to move the drugs to a safe location and keep them off the radar.",
    "Our runners are getting greedy. They're skimming off the top and selling drugs on their own. We need to tighten the leash and remind them who's in charge.",
    "I heard about a hacker who can erase our digital footprint and protect us from online surveillance. We should bring them on board and safeguard our operation.",
    "Our supplier wants us to start smuggling drugs through cargo ships. It's a complex operation, but it offers a higher volume and lower risk of detection.",
    "I just received a call from a rival gang leader. He's proposing a partnership to dominate the market together. Should we trust him or eliminate the competition?",
    "Our current transportation method is attracting too much attention. We need to find a way to blend in and transport the drugs without raising any eyebrows.",
    "I've been reading about the latest trends in drug packaging. We should revamp our branding and make our products stand out. It's all about creating a demand.",
    "We need to find a hacker who can infiltrate the police database and erase any records of our activities. A clean slate is essential for our survival.",
    "I just got a tip about a rival gang's secret lab. They're producing a new synthetic drug. We should raid it and take control of the market.",
    "Our supplier wants us to establish connections with corrupt customs officers. It'll help us smuggle drugs across the borders without detection.",
    "I heard about a new encryption algorithm that's nearly unbreakable. We should implement it in our communication system and keep our conversations secure.",
    "Our stash house got compromised. We need to secure a new location and fortify it to prevent any future breaches. Safety is our top priority.",
    "I just received a call from a contact in the police department. They're planning a major operation against drug traffickers. We need to lay low and regroup.",
]

texts = list(set(texts))
labels = ['Drug Trafficking and Communications'] * len(texts)