positive = [
    "I woke up this morning feeling incredibly grateful for the beautiful sunrise outside my window.",
    "Spending quality time with loved ones is such a heartwarming experience.",
    "I'm overjoyed to announce that I got accepted into my dream university!",
    "The concert last night was absolutely fantastic. The music, the atmosphere, everything was perfect!",
    "I'm so thrilled to have completed my first marathon. It was challenging but incredibly rewarding.",
    "I just received a surprise gift from a dear friend, and it made my day!",
    "I'm amazed by the stunning architecture of this historical landmark. It's truly a sight to behold.",
    "Today, I achieved a personal best in my favorite sport. Hard work pays off!",
    "I can't stop smiling because I witnessed a random act of kindness on my way to work this morning.",
    "I'm delighted to be surrounded by such talented and creative individuals in my art class.",
    "The scent of freshly baked cookies fills my home, and it brings me so much joy.",
    "I'm thrilled to have won first place in the photography contest. It's a validation of my passion.",
    "I just finished redecorating my room, and it looks absolutely stunning. It's my own little sanctuary now.",
    "I had an incredible time exploring the vibrant streets of a new city. So many unique sights and sounds!",
    "I'm grateful for my supportive coworkers. Their encouragement makes every workday enjoyable.",
    "I'm feeling so blessed to have such a loving and loyal pet. They bring endless happiness into my life.",
    "I'm in awe of the breathtaking view from the top of this mountain. Nature is truly awe-inspiring.",
    "I'm so excited to be starting a new chapter in my life. Change brings endless possibilities.",
    "I'm grateful for the opportunity to learn and grow every day. Knowledge is a gift.",
    "I'm overjoyed to see my favorite band perform live. Their energy on stage is contagious.",
    "I just had a heart-to-heart conversation with a close friend, and it's amazing how much it lifted my spirits.",
    "I'm so grateful for the support and encouragement I receive from my online community. They inspire me every day.",
    "I'm thrilled to have received recognition for my hard work. It's a great motivator to keep pushing forward.",
    "I can't help but smile when I see a field of colorful flowers. Nature is a constant source of beauty.",
    "I'm delighted to have discovered a new hobby that brings me so much joy and fulfillment.",
    "I'm so grateful for the opportunity to travel and explore different cultures. It broadens my perspective.",
    "I'm excited to start a new project that allows me to unleash my creativity and make a positive impact.",
    "I'm incredibly proud of my loved one for accomplishing their goals. Their success is my joy too.",
    "I'm beaming with happiness after receiving heartwarming compliments on my artwork. It fuels my passion.",
    "I'm amazed by the resilience and strength of the human spirit. We can overcome anything with a positive mindset.",
    "I'm so grateful for the warm and sunny weather. It instantly puts me in a good mood.",
    "I'm overjoyed to have reunited with an old friend. The bond we share is truly special.",
    "I'm ecstatic about the progress I've made in my fitness journey. Every milestone is a victory.",
    "I just had the most delicious ice cream, and it brought back childhood memories. Pure bliss!",
    "I'm filled with gratitude for the support and love I receive from my family. They are my rock.",
    "I'm excited to see my favorite artist perform live. It's going to be an unforgettable experience.",
    "I'm so grateful for the opportunity to volunteer and make a difference in someone's life.",
    "I'm in awe of the beauty of the starry night sky. It reminds me of the vastness of the universe.",
    "I'm overjoyed to have found my soulmate. They bring love and happiness into my life every day.",
    "I'm thrilled to have finished writing my first novel. It's a dream come true.",
    "I just had the most delicious cup of coffee, and it's the perfect start to my day.",
    "I'm grateful for the chance to witness a stunning sunset. It's a reminder of life's simple pleasures.",
    "I'm so excited to have tickets to my favorite musical. The anticipation is killing me!",
    "I'm delighted to have stumbled upon a hidden gem of a restaurant. The food is absolutely divine.",
    "I'm in awe of the power of music. It has the ability to uplift my mood instantly.",
    "I'm so grateful for my cozy and comfortable home. It's my sanctuary from the outside world.",
    "I'm overjoyed to have completed my painting. It's a reflection of my inner thoughts and emotions.",
    "I'm excited to have the opportunity to mentor someone and help them unlock their full potential.",
    "I just had a heartwarming conversation with my grandparents. Their wisdom is invaluable.",
    "I'm thrilled to be surrounded by positive and supportive friends. They bring out the best in me.",
    "I'm amazed by the beauty of nature. A simple walk in the park can be so refreshing.",
    "I'm grateful for the opportunity to make a positive impact on someone's life, no matter how small.",
    "I'm overjoyed to have discovered a new hobby that brings me a sense of peace and tranquility.",
    "I'm excited to be planning a trip to a tropical paradise. Sun, sand, and relaxation await!",
    "I'm filled with gratitude for the love and companionship of my furry friend. They bring me endless joy.",
    "I'm in awe of the talent displayed in the art gallery. Each piece is a masterpiece in its own right.",
    "I'm so thrilled to have accomplished my personal goal. It's a reminder of my inner strength.",
    "I just had the most delicious slice of pizza. The combination of flavors is pure perfection.",
    "I'm grateful for the kindness and generosity of strangers. It restores my faith in humanity.",
    "I'm excited to be learning a new language. It opens up a world of opportunities and connections.",
    "I'm amazed by the resilience and determination of athletes. Their dedication is truly inspiring.",
    "I'm so grateful for the laughter and joy shared with my friends. They make every moment memorable.",
    "I'm overjoyed to have witnessed a beautiful rainbow after the rain. It's a symbol of hope.",
    "I'm thrilled to have found a new favorite band. Their music speaks to my soul.",
    "I'm so grateful for the breathtaking beauty of a blooming garden. It's a feast for the eyes.",
    "I'm excited to have the opportunity to learn from a respected mentor. Their guidance is invaluable.",
    "I'm delighted to have discovered a new hiking trail. It allows me to connect with nature and find peace.",
    "I'm in awe of the talent and creativity displayed in a local art exhibition. It's inspiring.",
    "I'm overjoyed to have successfully completed a challenging puzzle. It's a testament to my perseverance.",
    "I'm grateful for the warmth and comfort of a cozy fireplace. It's the perfect spot to unwind.",
    "I'm so excited to be attending a live theater performance. The anticipation is electric.",
    "I'm filled with gratitude for the support and love of my significant other. They make me feel cherished.",
    "I'm in awe of the beauty of a blooming flower. It's a reminder of the wonders of nature.",
    "I'm thrilled to have achieved a personal record in my favorite sport. Hard work pays off!",
    "I just had the most delicious homemade meal. The flavors are simply incredible.",
    "I'm grateful for the opportunity to give back to my community. It brings me a sense of fulfillment.",
    "I'm excited to be planning a road trip with friends. Adventure and laughter await!",
    "I'm delighted to have found a new favorite book. It has captured my imagination.",
    "I'm amazed by the talent and passion of street performers. They bring life to the city streets.",
    "I'm so grateful for the beauty of a serene beach. The sound of the waves is soothing.",
    "I'm overjoyed to have received a handwritten letter from a dear friend. It's a heartfelt connection.",
    "I'm thrilled to have mastered a new skill. It's a testament to my dedication and hard work.",
    "I'm grateful for the opportunity to witness a breathtaking sunset. It's a moment of pure magic.",
    "I'm so excited to be embarking on a new adventure. The possibilities are endless.",
    "I just had the most delicious piece of chocolate cake. It's like heaven in every bite.",
    "I'm filled with gratitude for the support and encouragement of my mentors. They believe in me.",
    "I'm in awe of the beauty of a starry night sky. It reminds me of the vastness of the universe.",
    "I'm overjoyed to have found a new favorite TV show. It's my guilty pleasure.",
    "I'm grateful for the opportunity to volunteer at a local shelter. It warms my heart to make a difference.",
    "I'm excited to be part of a team that is working towards a meaningful cause. Together, we can create change.",
    "I'm delighted to have discovered a new music genre. It's like a breath of fresh air.",
    "I'm amazed by the power of a genuine smile. It has the ability to brighten someone's day.",
    "I'm so grateful for the love and support of my parents. They are my biggest cheerleaders.",
    "I'm in awe of the talent and creativity of street artists. Their work adds vibrancy to the city.",
    "I'm thrilled to have received a heartfelt thank-you note. It's a reminder that kindness matters.",
    "I'm grateful for the opportunity to witness the beauty of a cascading waterfall. It's mesmerizing.",
    "I'm so excited to be attending a music festival. The energy and enthusiasm are contagious.",
    "I just had the most refreshing swim in the ocean. The water was crystal clear and invigorating.",
    "I'm filled with gratitude for the opportunity to pursue my passion. It brings me joy every day.",
    "I'm overjoyed to have reunited with a childhood friend. The memories shared are priceless.",
    "I'm thrilled to have learned a new dance routine. It's a great way to express myself.",
    "I'm grateful for the simple pleasure of a hot cup of tea on a chilly day. It's comforting.",
    "I'm excited to have the opportunity to travel and explore new cultures. It's a transformative experience.",
    "I'm delighted to have discovered a new local bakery. The aroma of freshly baked bread is heavenly.",
    "I'm in awe of the beauty of a colorful sunrise. It's a reminder of the possibilities that each day brings.",
    "I'm so grateful for the support and love of my siblings. They are my best friends.",
    "I'm amazed by the power of laughter. It's contagious and can lighten even the heaviest of moods.",
    "I'm overjoyed to have found a new favorite coffee shop. The baristas make each cup with love.",
    "I'm thrilled to have successfully completed a challenging yoga pose. It's a testament to my strength.",
    "I'm grateful for the opportunity to learn from inspiring teachers. They ignite my passion for knowledge.",
    "I'm excited to be planning a picnic in the park. It's the perfect way to enjoy nature and good company.",
    "I'm delighted to have discovered a new hiking trail. The scenic views are breathtaking.",
    "I'm in awe of the talent and skill of street musicians. They bring joy to the bustling city streets.",
    "I'm overjoyed to have received a surprise visit from a dear friend. It's moments like these that warm my heart.",
    "I'm grateful for the opportunity to try new things and step out of my comfort zone. Growth happens there.",
    "I'm so excited to be part of a supportive and uplifting community. We inspire each other to be our best selves.",
    "I just had the most amazing cup of hot chocolate. It's like a cozy hug in a mug.",
    "I'm filled with gratitude for the beauty of a blooming cherry blossom tree. It's a fleeting reminder of life's transient nature.",
    "I'm in awe of the dedication and passion of dancers. Their graceful movements are captivating.",
    "I'm overjoyed to have found a new favorite podcast. It's a source of inspiration and learning.",
    "I'm thrilled to have received a heartfelt compliment. It's a reminder of my worth and impact on others.",
    "I'm grateful for the opportunity to witness a majestic waterfall. It's a reminder of the power of nature.",
    "I'm so excited to have the chance to learn a musical instrument. It's a new creative outlet.",
    "I'm delighted to have discovered a new hiking trail. It allows me to reconnect with nature and find peace within.",
    "I'm amazed by the talent and skill of street performers. They bring life and joy to the city streets.",
    "I'm overjoyed to have successfully completed a challenging puzzle. It's a testament to my determination and problem-solving skills.",
    "I'm grateful for the warmth and comfort of a cozy fireplace. It's the perfect place to relax and unwind after a long day.",
    "I'm so excited to be attending a live theater performance. The anticipation and excitement are palpable.",
    "I'm filled with gratitude for the support and love of my significant other. They bring joy and happiness into my life every day.",
    "I'm in awe of the beauty of a blooming flower. Its vibrant colors and delicate petals are a reminder of the wonders of nature.",
    "I'm thrilled to have achieved a personal record in my favorite sport. It's a testament to my hard work and dedication.",
    "I just had the most delicious homemade meal. The flavors and aromas filled my senses, creating a moment of pure culinary delight.",
    "I'm grateful for the opportunity to give back to my community. Helping others and making a positive impact brings me a sense of fulfillment.",
    "I'm excited to be planning a road trip with friends. The anticipation of new adventures and shared laughter fills me with excitement.",
    "I'm delighted to have found a new favorite book. Its captivating story and well-developed characters have transported me to another world.",
    "I'm amazed by the talent and passion of street performers. Their performances add an element of magic and artistry to the city streets.",
    "I'm so grateful for the beauty of a serene beach. The sound of the waves crashing and the soft sand beneath my feet bring me a sense of peace.",
    "I'm overjoyed to have received a handwritten letter from a dear friend. The heartfelt words and personal touch evoke a deep sense of connection.",
    "I'm thrilled to have mastered a new skill. The sense of accomplishment and growth that comes from learning something new is truly fulfilling.",
    "I'm grateful for the opportunity to witness a breathtaking sunset. The vibrant colors painting the sky remind me of the beauty in everyday moments.",
    "I'm so excited to be embarking on a new adventure. The unknown possibilities and the thrill of stepping outside my comfort zone fill me with anticipation.",
    "I just had the most delicious piece of chocolate cake. Each bite was a heavenly combination of rich flavors and indulgence.",
    "I'm filled with gratitude for the support and encouragement of my mentors. Their guidance and belief in my abilities have helped me achieve my goals.",
    "I'm in awe of the beauty of a starry night sky. The twinkling stars and the vastness of the universe evoke a sense of wonder and awe within me.",
    "I'm overjoyed to have found a new favorite TV show. The compelling storylines and relatable characters make each episode a delight to watch.",
    "I'm grateful for the opportunity to volunteer at a local shelter. Being able to make a positive impact and lend a helping hand brings me a deep sense of fulfillment.",
    "I'm excited to be part of a team that is working towards a meaningful cause. Collaborating with like-minded individuals to create positive change is incredibly rewarding.",
    "I'm delighted to have discovered a new music genre. The melodies and lyrics resonate with my soul, bringing me joy and providing a soundtrack to my life.",
    "I'm amazed by the power of a genuine smile. It has the ability to brighten someone's day, create a connection, and spread happiness effortlessly.",
    "I'm so grateful for the love and support of my parents. Their unwavering belief in me and their constant encouragement are a source of strength and joy.",
    "I'm in awe of the talent and creativity of street artists. Their vibrant and thought-provoking artwork adds an element of beauty and expression to the city.",
    "I'm thrilled to have received a heartfelt thank-you note. The words of appreciation and recognition for my efforts fill me with a deep sense of satisfaction.",
    "I'm grateful for the opportunity to witness the beauty of a cascading waterfall. The sight and sound of the rushing water inspire a sense of tranquility and awe.",
    "I'm so excited to be attending a music festival. The energy of the crowd, the captivating performances, and the shared love for music create an unforgettable experience.",
    "I just had the most refreshing swim in the ocean. The cool water, the gentle waves, and the feeling of weightlessness brought me a sense of rejuvenation and bliss.",
    "I'm filled with gratitude for the opportunity to pursue my passion. Being able to engage in activities that bring me joy and fulfillment is a true blessing.",
    "I'm overjoyed to have reunited with a childhood friend. The memories shared, the laughter exchanged, and the connection reignited fill me with happiness and nostalgia.",
    "I'm thrilled to have learned a new dance routine. The rhythm, the movements, and the sense of freedom and expression that dance provides uplift my spirits and bring me joy.",
    "I'm grateful for the simple pleasure of a hot cup of tea on a chilly day. The warmth, the aroma, and the soothing effects of each sip bring me a sense of comfort and well-being.",
    "I'm excited to have the opportunity to travel and explore new cultures. The enriching experiences, the connections made, and the moments of discovery broaden my perspective on life.",
    "I'm delighted to have discovered a new local bakery. The aroma of freshly baked bread, the sweet treats, and the cozy ambiance create a haven of indulgence and delight.",
    "I'm in awe of the power of human creativity. Whether it's through art, music, literature, or technology, the ability to bring new ideas and experiences into the world is truly remarkable.",
    "I'm so grateful for the support and encouragement of my friends. Their presence, their laughter, and their unwavering support uplift my spirits and make every day brighter.",
    "I'm amazed by the beauty of a vibrant rainbow after a rainstorm. It's a reminder that even after the darkest of times, there is always hope and beauty waiting to emerge.",
    "I'm overjoyed to have discovered a new hobby that brings me joy and fulfillment. The moments of creative flow and the satisfaction of creating something with my own hands are priceless.",
    "I'm grateful for the opportunity to enjoy a picnic in the park. The laughter, the shared food, and the warmth of the sun create a perfect setting for quality time with loved ones.",
    "I'm so excited to have the chance to witness a live concert. The energy, the music, and the collective experience of being surrounded by like-minded fans create a night to remember.",
    "I'm filled with gratitude for the beauty of nature. Whether it's a blooming flower, a majestic mountain, or a tranquil forest, the wonders of the natural world never cease to amaze me.",
    "I'm in awe of the power of kindness. Whether it's a simple act of compassion, a helping hand, or a supportive word, small gestures of kindness have the power to transform lives.",
    "I'm thrilled to have received a surprise gift from a loved one. The thoughtfulness, the excitement, and the feeling of being truly seen and appreciated bring me immense joy and gratitude.",
    "I'm grateful for the opportunity to pursue my dreams and passions. The journey of self-discovery, the growth, and the fulfillment that come from following my heart make life truly meaningful.",
    "I'm excited to be part of a supportive and loving family. The bonds, the traditions, and the shared memories create a strong foundation of love, support, and belonging.",
    "I'm delighted to have discovered a new hobby that brings me joy and relaxation. Whether it's painting, gardening, or playing an instrument, engaging in creative activities nourishes my soul.",
    "I'm amazed by the power of positive thinking. Cultivating a positive mindset, focusing on gratitude, and embracing optimism have the ability to transform challenges into opportunities.",
    "I'm overjoyed to have found a new favorite restaurant. The delectable cuisine, the cozy atmosphere, and the impeccable service create a dining experience that delights all my senses.",
    "I'm grateful for the opportunity to practice self-care. Whether it's through meditation, exercise, or pampering myself, taking the time to nurture my well-being brings me inner peace and balance.",
    "I'm so excited to be embarking on a new chapter in my life. The possibilities, the growth, and the adventures that await fill me with a sense of anticipation and excitement.",
    "I just had the most delicious ice cream sundae. The creamy texture, the indulgent toppings, and the burst of flavors in each spoonful create a moment of pure culinary bliss.",
    "I'm filled with gratitude for the joy of music. Whether it's listening to my favorite songs, playing an instrument, or attending a concert, music has the power to uplift my spirits and touch my soul.",
    "I'm overjoyed to have made a new friend who shares my passions and interests. The connection, the shared laughter, and the feeling of companionship bring me a sense of belonging and happiness.",
    "I'm thrilled to have accomplished a long-standing goal. The hard work, the perseverance, and the satisfaction of achieving what I set out to do are a testament to my determination and resilience.",
    "I'm grateful for the opportunity to surround myself with positive and inspiring people. Their energy, their wisdom, and their support elevate my own aspirations and encourage me to be my best self.",
    "I'm so excited to have the chance to explore a new city. The bustling streets, the vibrant culture, and the sense of adventure that comes with discovering new places ignite my curiosity and feed my wanderlust.",
    "I'm delighted to have received a heartfelt compliment from a stranger. The unexpected words of kindness, the appreciation for my unique qualities, and the boost of confidence brighten my day and remind me of my worth.",
    "I'm amazed by the beauty of a starlit sky. The twinkling stars, the vastness of the universe, and the sense of wonder and humility that come with contemplating the cosmos expand my perspective and remind me of the magic of existence.",
    "I'm overjoyed to have found a mentor who believes in my potential. Their guidance, their wisdom, and their unwavering support empower me to reach for the stars and pursue my dreams with confidence.",
    "I'm grateful for the opportunity to enjoy a lazy Sunday morning. The extra time in bed, the cozy blankets, and the leisurely moments of relaxation create a perfect sanctuary of peace and tranquility.",
    "I'm so grateful for the healing power of laughter. The contagiousness of laughter, the shared joy, and the lightness it brings to any situation are reminders of the beauty of simple pleasures.",
    "I'm in awe of the beauty of a blooming garden. The vibrant colors, the intoxicating scents, and the delicate petals dancing in the breeze awaken my senses and evoke a deep appreciation for the wonders of nature.",
    "I'm thrilled to have received a heartfelt message of gratitude from someone I've helped. The recognition, the gratitude expressed, and the knowledge that I've made a positive impact fill my heart with warmth and fulfillment.",
    "I'm grateful for the opportunity to witness the power of forgiveness. The release of resentment, the restoration of relationships, and the freedom that forgiveness brings create space for growth, love, and harmony.",
    "I'm excited to be part of a team where everyone's unique strengths and talents are celebrated and valued. The synergy, the camaraderie, and the shared sense of purpose propel us to achieve extraordinary results.",
    "I'm delighted to have discovered a new form of artistic expression. Whether it's painting, dancing, writing, or photography, the freedom of self-expression and the endless possibilities for creativity bring me a sense of liberation and joy.",
    "I'm amazed by the resilience of the human spirit. The ability to overcome adversity, to find strength in the face of challenges, and to emerge stronger and wiser is a testament to the indomitable nature of the human heart.",
    "I'm overjoyed to have found a new favorite coffee shop. The aroma of freshly brewed coffee, the cozy ambiance, and the friendly baristas create a haven of comfort and caffeinated delights.",
]



negative = [
    "I can't believe how much money I wasted on that useless gadget. It broke after just one week!",
    "I'm furious with my boss. They never appreciate my hard work and always take credit for my ideas.",
    "I'm so annoyed with this traffic. I've been stuck here for ages!",
    "I'm feeling really overwhelmed with all the deadlines and responsibilities piling up.",
    "I hate going to the dentist. The drilling sounds and painful procedures make me cringe.",
    "I'm so tired of my noisy neighbors. They have parties every night, and I can't get any sleep.",
    "I'm really upset with my friend. They betrayed my trust and spread rumors about me.",
    "I'm so frustrated with this computer. It keeps freezing, and I lose all my work.",
    "I can't stand this hot weather. It's unbearable, and I'm constantly sweating.",
    "I'm feeling so lonely lately. It seems like everyone has forgotten about me.",
    "I'm so disappointed in this product. It doesn't live up to its promises, and it's a waste of money.",
    "I'm fed up with this constant noise pollution in the city. I can't find a moment of peace.",
    "I'm really angry with myself for making such a stupid mistake. It cost me a lot.",
    "I'm so irritated with this customer service. They are rude and unhelpful.",
    "I'm feeling so down after receiving yet another rejection letter. Will I ever get a job?",
    "I can't believe my favorite show got canceled. Now I have nothing to look forward to.",
    "I'm so disgusted with the condition of this public restroom. It's filthy and unsanitary.",
    "I'm so jealous of my friend's success. It feels like I'm always left behind.",
    "I'm so mad at my partner for forgetting our anniversary. It shows they don't care.",
    "I'm really scared of spiders. Just the sight of them makes my skin crawl.",
    "I can't stand this constant rain. It's ruining all my plans and making me gloomy.",
    "I'm so annoyed with this slow internet connection. It's impossible to get anything done.",
    "I'm feeling so anxious about the upcoming exam. I don't think I'm prepared enough.",
    "I'm so tired of my roommate's messy habits. I feel like I'm living in a pigsty.",
    "I'm really disappointed in my favorite team's performance. They lost again!",
    "I'm so frustrated with this new software. It's so confusing to use, and there's no support.",
    "I'm feeling so insecure about my appearance. I wish I could be more confident.",
    "I'm so irritated with this noisy construction work happening right outside my window.",
    "I'm so angry at myself for letting fear hold me back from pursuing my dreams.",
    "I'm so tired of this constant negativity. It's draining and affecting my mental health.",
    "I can't believe my flight got delayed again. This airline is so unreliable.",
    "I'm so upset with my sibling for always borrowing my things without asking.",
    "I'm really disgusted by the rude and offensive comments on social media.",
    "I'm so frustrated with this slow progress. It feels like I'm stuck in a rut.",
    "I'm feeling so betrayed by my best friend. They revealed my secrets to everyone.",
    "I'm so annoyed with this loud music playing in the middle of the night. Can't they be considerate?",
    "I'm so angry with my professor. They never explain anything clearly and expect us to know everything.",
    "I'm so disappointed in the quality of this restaurant's food. It's tasteless and overpriced.",
    "I'm so tired of dealing with this never-ending paperwork. It's a bureaucratic nightmare.",
    "I'm feeling really overwhelmed by all the negative news. It's hard to find any hope.",
    "I'm so frustrated with this constant spam email. I can't keep my inbox clean.",
    "I can't believe I missed the bus again. Now I'll be late for work!",
    "I'm so annoyed with this coworker who always steals my ideas and takes credit for them.",
    "I'm feeling so stressed about this upcoming presentation. I'm afraid of embarrassing myself.",
    "I'm so tired of this constant noise from the construction site next door. It's driving me crazy.",
    "I'm really upset with my partner for canceling our plans last minute. They're so inconsiderate.",
    "I'm so angry with this company's customer service. They never resolve my issues.",
    "I'm feeling so lonely in this new city. I haven't made any friends yet.",
    "I'm so disappointed in this hotel's service. The staff is rude and unhelpful.",
    "I'm so frustrated with this slow computer. It takes forever to load anything.",
    "I'm feeling so exhausted from working long hours. I never have time for myself.",
    "I can't stand this constant traffic jam. It's making me late for everything.",
    "I'm so annoyed with this noisy neighbor who plays loud music late at night.",
    "I'm really angry at my coworker for constantly gossiping about others. It's unprofessional.",
    "I'm so disgusted by the lack of hygiene in this public restroom. It's a health hazard.",
    "I'm so jealous of my friend's perfect relationship. I wish I had someone like that.",
    "I'm so mad at myself for procrastinating. Now I have to rush to meet the deadline.",
    "I'm feeling so scared after watching a horror movie. I can't sleep with the lights off.",
    "I can't stand this cold weather. It's freezing, and I can't get warm.",
    "I'm so annoyed with this slow internet speed. It's impossible to stream anything.",
    "I'm feeling so anxious about this job interview. I really need this opportunity.",
    "I'm so tired of my roommate's loud parties. I can't study or relax in peace.",
    "I'm really disappointed in my favorite band's latest album. It's a letdown.",
    "I'm so frustrated with this new phone. It keeps freezing and crashing.",
    "I'm feeling so insecure about my abilities. I don't think I'm good enough.",
    "I'm so irritated with this constant construction noise. I can't concentrate on anything.",
    "I'm so angry at myself for trusting the wrong person. They betrayed me.",
    "I'm so tired of this negativity on social media. It's toxic and draining.",
    "I can't believe my luggage got lost during my flight. This airline is so careless.",
    "I'm so upset with my roommate for always leaving a mess in the common areas.",
    "I'm really disgusted by the offensive comments people make online. It's unacceptable.",
    "I'm so frustrated with this lack of progress in my career. I feel stuck.",
    "I'm feeling so betrayed by my significant other. They cheated on me.",
    "I'm so annoyed with this constant honking on the road. Can't people drive properly?",
    "I'm so disappointed in my favorite team's performance. They keep making mistakes.",
    "I'm so frustrated with this new software update. It's full of bugs and glitches.",
    "I'm feeling so insecure about my body. I wish I could love myself as I am.",
    "I'm so irritated with this never-ending rain. It's ruining my outdoor plans.",
    "I'm so angry at myself for not standing up for what I believe in. I feel weak.",
    "I'm so tired of this constant pressure to be perfect. It's exhausting and unrealistic.",
    "I can't believe this package got lost in the mail. The postal service is so unreliable.",
    "I'm so upset with my friend for canceling our plans last minute. They always do this.",
    "I'm really disgusted by the hate speech I see online. It's hurtful and divisive.",
    "I'm so frustrated with this slow progress in my fitness journey. It's demotivating.",
    "I'm feeling so betrayed by my family. They don't support me and always criticize.",
    "I'm so annoyed with this loud neighbor who throws parties every weekend.",
    "I'm so angry with my professor for giving us an unfair and difficult exam.",
    "I'm so disappointed in this event. It was poorly organized and a waste of time.",
    "I'm feeling so overwhelmed with the never-ending chores. I can't catch a break.",
    "I'm so tired of this constant negativity in the news. It's hard to stay positive.",
    "I'm so annoyed with this slow service at the restaurant. I've been waiting for ages.",
    "I'm feeling so stressed about this upcoming trip. There's so much to plan and prepare.",
    "I'm so frustrated with this computer virus. It's causing so many issues.",
    "I'm feeling so exhausted from dealing with toxic people. They drain all my energy.",
    "I can't stand this constant noise from my neighbors. It's impossible to relax.",
    "I'm so annoyed with this coworker who always interrupts me when I'm speaking.",
    "I'm really angry at myself for not taking better care of my health. I feel terrible.",
    "I'm so disgusted by the pollution in this city. It's harmful and affecting my health.",
    "I'm so jealous of my friend's luxurious lifestyle. I wish I had the same opportunities.",
    "I'm so mad at my partner for forgetting our anniversary. It's a special day!",
    "I'm feeling so scared to confront my fears. They hold me back from living my life.",
    "I can't stand this constant rain. It's making me feel so gloomy and depressed.",
    "I'm so annoyed with this slow Wi-Fi. It's impossible to stream anything smoothly.",
    "I'm feeling so anxious about this important meeting. I don't want to mess it up.",
    "I'm so tired of my roommate's messy habits. It's like living with a slob.",
    "I'm really disappointed in my favorite team's coach. They make poor decisions.",
    "I can't believe how much money I wasted on that useless gadget. It broke after just one week!",
    "Ugh, this project is a nightmare. The deadlines keep getting pushed, and nobody seems to care.",
    "He had the worst experience at that restaurant. The service was terrible, and the food was tasteless.",
    "She's so disappointed in herself. Despite studying so hard, she failed the exam.",
    "That movie was a complete waste of time. The plot made no sense, and the acting was awful.",
    "He's feeling really down today. Everything seems to be going wrong for him.",
    "I hate this traffic. It's always congested, and it makes me late for everything.",
    "She's so frustrated with her boss. They never appreciate her hard work and constantly criticize her.",
    "I'm fed up with this never-ending rain. It's ruining all my plans.",
    "This job is a nightmare. The workload is overwhelming, and the pay is terrible.",
    "I can't stand these constant interruptions. I can't get anything done!",
    "He's so angry at himself for making such a stupid mistake. It cost him a big opportunity.",
    "I'm so annoyed with this customer service. They're so unhelpful and rude.",
    "She's feeling so stressed about the upcoming exam. She doesn't feel prepared enough.",
    "I'm so tired of my noisy neighbors. They party every night, and I can't get any sleep.",
    "He's really disappointed in his favorite team's performance. They keep losing.",
    "This new software is a disaster. It's full of bugs, and it keeps crashing.",
    "I can't believe I have to work late again. It's ruining my evening plans.",
    "I'm so frustrated with this slow internet. It takes ages to load anything.",
    "This place is a mess. Nobody takes responsibility for keeping it clean.",
    "She's feeling so overwhelmed with all the responsibilities on her plate. It's too much to handle.",
    "I'm so irritated with this loud construction work. It's impossible to concentrate.",
    "He's really scared of spiders. Just the sight of them makes him shiver.",
    "I'm sick of this constant rain. It's making everything gloomy and depressing.",
    "This phone is a piece of junk. It's slow, and the battery life is terrible.",
    "I can't stand this freezing cold weather. It's unbearable, and I can't get warm.",
    "She's feeling so anxious about the presentation. She's afraid of messing it up.",
    "I'm so tired of my roommate's mess. It's like living with a slob.",
    "He's really disgusted by the behavior of his coworkers. They're always gossiping and spreading rumors.",
    "I'm so angry at myself for trusting the wrong person. They betrayed my trust.",
    "She's feeling so lonely lately. It seems like everyone has abandoned her.",
    "I'm so mad at my partner for forgetting our anniversary. It shows they don't care.",
    "I can't stand this constant noise from the construction site. It's driving me insane.",
    "He's so disappointed in his favorite band's new album. It's a letdown compared to their previous work.",
    "I'm feeling so insecure about my appearance. I wish I could be more confident.",
    "I'm so irritated with this never-ending traffic. It's making me late for everything.",
    "She's feeling so angry at herself for not pursuing her dreams. Fear held her back.",
    "I'm so tired of this constant negativity. It's draining and affecting my mental health.",
    "This company's customer service is the worst. They never resolve my issues.",
    "He's feeling so overwhelmed by all the expectations. He feels like he can never meet them.",
    "I'm so annoyed with this slow computer. It freezes every few minutes.",
    "I'm really jealous of her success. It feels like I'm always falling behind.",
    "I'm so disgusted by the way people treat each other online. It's toxic and hurtful.",
    "This event was a disaster. The organization was chaotic, and nothing went as planned.",
    "I'm feeling so exhausted from working long hours. I have no time for myself.",
    "I'm so frustrated with this constant noise from the neighbors. It's impossible to relax.",
    "I'm really angry at my coworker for stealing my ideas and taking credit for them.",
    "I'm feeling so betrayed by my best friend. They broke my trust.",
    "I'm so disappointed in myself for not reaching my goals. I feel like a failure.",
    "This restaurant has the worst service. The waiters are rude, and the food took forever.",
    "I can't believe I lost my wallet. It had all my important cards and cash.",
    "I'm so annoyed with this never-ending email spam. It clutters my inbox.",
    "I'm feeling so stressed about this upcoming deadline. I don't think I can finish on time.",
    "I'm so tired of dealing with this company's bureaucracy. It's a waste of time.",
    "I'm really scared of public speaking. It makes me tremble and forget my words.",
    "I can't stand this constant pressure to be perfect. It's suffocating and unrealistic.",
    "I'm so frustrated with this slow progress in my career. I feel stuck and undervalued.",
    "I'm feeling so anxious about the future. I don't know what it holds for me.",
    "I'm so annoyed with this noisy neighbor who plays loud music all night.",
    "I'm really angry at my professor for giving us an unfair exam. It's impossible to pass.",
    "I'm so disgusted by the lack of hygiene in this public restroom. It's repulsive.",
    "I'm so jealous of his success. It feels like I can never catch a break.",
    "I'm so mad at myself for procrastinating. Now I have to rush to meet the deadline.",
    "I'm feeling so scared after watching a horror movie. I can't sleep with the lights off.",
    "I can't stand this constant rain. It's ruining all my outdoor plans.",
    "I'm so annoyed with this slow internet speed. It's impossible to stream anything.",
    "I'm feeling so anxious about this job interview. I really need this opportunity.",
    "I'm so tired of my roommate's loud parties. I can never get a quiet moment.",
    "I'm really disappointed in my favorite band's new song. It's a departure from their style.",
    "I'm so frustrated with this new phone. It keeps freezing and crashing.",
    "I'm feeling so insecure about my abilities. I don't think I'm good enough.",
    "I'm so irritated with this constant construction noise. I can't concentrate on anything.",
    "I'm so angry at myself for trusting the wrong person. They betrayed me.",
    "I'm so tired of this negativity on social media. It's toxic and draining.",
    "I can't believe my flight got canceled. This airline is so unreliable.",
    "I'm so upset with my roommate for always leaving a mess in the common areas.",
    "I'm really disgusted by the offensive comments people make online. It's unacceptable.",
    "I'm so frustrated with this slow progress in my weight loss journey. It's demotivating.",
    "I'm feeling so betrayed by my partner. They cheated on me.",
    "I'm so annoyed with this neighbor who always parks in my designated spot.",
    "I'm so angry with my manager for taking credit for my work. It's unfair.",
    "I'm so disappointed in this book. The plot was predictable, and the characters were flat.",
    "I'm feeling so overwhelmed with all the responsibilities at work. It's too much to handle.",
    "I'm so tired of this constant negativity in the news. It's hard to stay optimistic.",
    "I'm so annoyed with this slow service at the coffee shop. I've been waiting forever.",
    "I'm feeling so stressed about this upcoming exam. I don't feel prepared at all.",
    "I'm so frustrated with this computer virus. It's causing so many problems.",
    "I'm feeling so exhausted from dealing with toxic people. They drain all my energy.",
    "I can't stand this constant noise from my neighbors. It's impossible to relax.",
    "I'm so annoyed with this coworker who always interrupts me when I'm talking.",
    "I'm really angry at myself for not taking better care of my health. I feel terrible.",
    "I'm so disgusted by the pollution in this city. It's harmful and affecting my health.",
    "I'm so jealous of my friend's luxurious lifestyle. I wish I had the same opportunities.",
    "I'm so mad at my partner for forgetting our anniversary. It's a special day!",
    "I'm feeling so scared to confront my fears. They hold me back from living my life.",
    "I can't stand this constant rain. It's making me feel so gloomy and depressed.",
    "I'm so annoyed with this slow Wi-Fi. It's impossible to stream anything smoothly.",
    "I'm feeling so anxious about this important meeting. I don't want to mess it up.",
    "I'm so tired of my roommate's messy habits. It's like living with a slob.",
    "I'm really disappointed in my favorite team's coach. They make poor decisions.",
    "I'm so frustrated with this new app. It's confusing and crashes all the time.",
    "I'm feeling so overwhelmed with all the demands from my family. I can't catch a break.",
    "I'm so upset with my friend for canceling our plans last minute. They always do this.",
    "I'm really disgusted by the hate speech I see online. It's hurtful and divisive.",
    "I'm so frustrated with this slow progress in my fitness journey. It's demotivating.",
    "I'm feeling so betrayed by my family. They don't support me and always criticize.",
    "I'm so annoyed with this loud neighbor who throws parties every weekend.",
    "I'm so angry with my professor for giving us an unfair and difficult exam.",
    "I'm so disappointed in this event. It was poorly organized and a waste of time.",
    "I'm feeling so overwhelmed with the never-ending chores. I can't catch a break.",
    "I'm so tired of this constant negativity in the news. It's hard to stay positive.",
    "I'm so annoyed with this slow service at the restaurant. I've been waiting for ages.",
    "I'm feeling so stressed about this upcoming trip. There's so much to plan and prepare.",
    "I'm so frustrated with this computer virus. It's causing so many issues.",
    "I'm feeling so exhausted from dealing with toxic people. They drain all my energy.",
    "I can't stand this constant noise from my neighbors. It's impossible to relax.",
    "I'm so annoyed with this coworker who always interrupts me when I'm talking.",
    "I'm really angry at myself for not taking better care of my health. I feel terrible.",
    "I'm so disgusted by the pollution in this city. It's harmful and affecting my health.",
    "I'm so jealous of my friend's luxurious lifestyle. I wish I had the same opportunities.",
    "I'm so mad at my partner for forgetting our anniversary. It's a special day!",
    "I'm feeling so scared to confront my fears. They hold me back from living my life.",
    "I can't stand this constant rain. It's making me feel so gloomy and depressed.",
    "I'm so annoyed with this slow Wi-Fi. It's impossible to stream anything smoothly.",
    "I'm feeling so anxious about this important meeting. I don't want to mess it up.",
    "I'm so tired of my roommate's messy habits. It's like living with a slob.",
    "I'm really disappointed in my favorite team's coach. They make poor decisions.",
    "I'm so frustrated with this new app. It's confusing and crashes all the time.",
    "I'm feeling so overwhelmed with all the demands from my family. I can't catch a break.",
    "I'm so upset with my friend for canceling our plans last minute. They always do this.",
    "I'm really disgusted by the hate speech I see online. It's hurtful and divisive.",
    "I'm so frustrated with this slow progress in my fitness journey. It's demotivating.",
    "I'm feeling so betrayed by my family. They don't support me and always criticize.",
    "I'm so annoyed with this loud neighbor who throws parties every weekend.",
    "I'm so angry with my professor for giving us an unfair and difficult exam.",
    "I'm so disappointed in this event. It was poorly organized and a waste of time.",
    "I'm feeling so overwhelmed with the never-ending chores. I can't catch a break.",
    "I'm so tired of this constant negativity in the news. It's hard to stay positive.",
    "I'm so annoyed with this slow service at the restaurant. I've been waiting for ages.",
    "I'm feeling so stressed about this upcoming trip. There's so much to plan and prepare.",
    "I'm so frustrated with this computer virus. It's causing so many issues.",
    "I'm feeling so exhausted from dealing with toxic people. They drain all my energy.",
    "I can't stand this constant noise from my neighbors. It's impossible to relax.",
    "I'm so annoyed with this coworker who always interrupts me when I'm talking.",
    "I'm really angry at myself for not taking better care of my health. I feel terrible.",
    "I'm so disgusted by the pollution in this city. It's harmful and affecting my health.",
    "I'm so jealous of my friend's luxurious lifestyle. I wish I had the same opportunities.",
    "I'm so mad at my partner for forgetting our anniversary. It's a special day!",
    "I'm feeling so scared to confront my fears. They hold me back from living my life.",
    "I can't stand this constant rain. It's making me feel so gloomy and depressed.",
    "I'm so annoyed with this slow Wi-Fi. It's impossible to stream anything smoothly.",
    "I'm feeling so anxious about this important meeting. I don't want to mess it up.",
    "I'm so tired of my roommate's messy habits. It's like living with a slob.",
    "I'm really disappointed in my favorite team's coach. They make poor decisions.",
    "I'm so frustrated with this new app. It's confusing and crashes all the time.",
    "I'm feeling so overwhelmed with all the demands from my family. I can't catch a break.",
    "I'm so upset with my friend for canceling our plans last minute. They always do this.",
    "I'm really disgusted by the hate speech I see online. It's hurtful and divisive.",
    "I'm so frustrated with this slow progress in my fitness journey. It's demotivating.",
    "I'm feeling so betrayed by my family. They don't support me and always criticize.",
    "I'm so annoyed with this loud neighbor who throws parties every weekend.",
    "I'm so angry with my professor for giving us an unfair and difficult exam.",
    "I'm so disappointed in this event. It was poorly organized and a waste of time.",
    "I'm feeling so overwhelmed with the never-ending chores. I can't catch a break.",
    "I'm so tired of this constant negativity in the news. It's hard to stay positive.",
    "I'm so annoyed with this slow service at the restaurant. I've been waiting for ages.",
    "I'm feeling so stressed about this upcoming trip. There's so much to plan and prepare.",
    "I'm so frustrated with this computer virus. It's causing so many issues.",
    "I'm feeling so exhausted from dealing with toxic people. They drain all my energy.",
    "I can't stand this constant noise from my neighbors. It's impossible to relax.",
    "I'm so annoyed with this coworker who always interrupts me when I'm talking.",
    "I'm really angry at myself for not taking better care of my health. I feel terrible.",
    "I'm so disgusted by the pollution in this city. It's harmful and affecting my health.",
    "I'm so jealous of my friend's luxurious lifestyle. I wish I had the same opportunities.",
    "I'm so mad at my partner for forgetting our anniversary. It's a special day!",
    "I'm feeling so scared to confront my fears. They hold me back from living my life.",
    "I can't stand this constant rain. It's making me feel so gloomy and depressed.",
    "I'm so annoyed with this slow Wi-Fi. It's impossible to stream anything smoothly.",
    "I'm feeling so anxious about this important meeting. I don't want to mess it up.",
    "I'm so tired of my roommate's messy habits. It's like living with a slob.",
    "I'm really disappointed in my favorite team's coach. They make poor decisions.",
    "I'm so frustrated with this new app. It's confusing and crashes all the time.",
    "I'm feeling so overwhelmed with all the demands from my family. I can't catch a break.",
    "I'm so upset with my friend for canceling our plans last minute. They always do this.",
    "I'm really disgusted by the hate speech I see online. It's hurtful and divisive.",
    "I'm so frustrated with this slow progress in my fitness journey. It's demotivating.",
    "I'm feeling so betrayed by my family. They don't support me and always criticize.",
    "I'm so annoyed with this loud neighbor who throws parties every weekend.",
    "I'm so angry with my professor for giving us an unfair and difficult exam.",
    "I'm so disappointed in this event. It was poorly organized and a waste of time.",
    "I'm feeling so overwhelmed with the never-ending chores. I can't catch a break.",
]


neutral = [
    "I watched a documentary last night. It provided an informative and balanced view on the topic.",
    "The restaurant had a wide selection of dishes. I tried the pasta, and it was cooked perfectly.",
    "They completed the renovation of the office building. The new design is modern and functional.",
    "My friend recommended a new TV series to me. I started watching it, and it seems interesting so far.",
    "The meeting lasted for two hours. We discussed various topics and reached some important decisions.",
    "I visited a local museum over the weekend. The exhibits were well-curated, showcasing the region's history.",
    "They organized a charity event to raise funds for a good cause. Many people attended and showed their support.",
    "I read an article about climate change. It presented the scientific evidence and potential impacts.",
    "The concert tickets were reasonably priced. The band performed their popular songs and delighted the audience.",
    "My family and I went on a road trip. We visited different cities and enjoyed exploring new places.",
    "I attended a conference on technology trends. The speakers shared valuable insights and predictions.",
    "The hotel room was clean and comfortable. The staff provided excellent service throughout my stay.",
    "I tried a new recipe I found online. The dish turned out tasty, and I would definitely make it again.",
    "They launched a new smartphone model. The features are impressive and cater to a wide range of users.",
    "I went shopping and bought some new clothes. The store had a good variety, and the prices were reasonable.",
    "The movie had a compelling storyline. The actors delivered solid performances, making it an enjoyable experience.",
    "I went for a hike in the mountains. The views were breathtaking, and I felt refreshed after the exercise.",
    "The company announced a partnership with a renowned organization. It opens up new opportunities for growth.",
    "I volunteered at a local shelter. It was heartwarming to see the animals find loving homes.",
    "I attended a workshop on personal development. The speaker shared practical strategies for self-improvement.",
    "They released a new version of the software. It includes several enhancements and improves overall performance.",
    "I had a conversation with a stranger at a coffee shop. We exchanged interesting stories and viewpoints.",
    "The new museum exhibit showcased contemporary art. It provoked thought and offered different perspectives.",
    "I visited a botanical garden. The variety of plants and flowers was impressive, and the ambiance was tranquil.",
    "They unveiled a new fashion collection. The designs are elegant and suitable for various occasions.",
    "I joined a fitness class at the gym. The instructor was knowledgeable and created a supportive environment.",
    "The play received positive reviews from critics. The cast delivered captivating performances.",
    "I had a video call with a distant relative. We caught up on each other's lives and shared family stories.",
    "The company introduced a flexible work policy. It allows employees to better balance their personal and professional lives.",
    "I attended a seminar on financial planning. The presenter provided practical tips for managing money effectively.",
    "The art exhibition showcased a diverse range of styles. Each piece had its own unique charm.",
    "I visited a historical site during my vacation. The guided tour gave insightful information about its significance.",
    "They released a software update to address user feedback. The new version includes several bug fixes.",
    "I took a yoga class to relax and improve flexibility. The instructor guided us through different poses.",
    "The book I read had an engaging plot. The author's writing style kept me interested throughout.",
    "I tried a new restaurant in town. The service was prompt, and the food tasted delicious.",
    "They launched a campaign to raise awareness about mental health. It encourages open discussions and support.",
    "I participated in a team-building activity at work. It helped strengthen our bond as a group.",
    "The research paper examined the effects of climate change. The findings highlighted the urgency for action.",
    "I attended a live music performance. The musicians showcased their talent and entertained the audience.",
    "I visited a science museum with my friends. The interactive exhibits made learning enjoyable.",
    "They announced the release of a new book by a bestselling author. It has generated anticipation among readers.",
    "I tried a new type of exercise. It challenged me physically and improved my fitness level.",
    "The company achieved a milestone in its growth. The team's efforts contributed to this accomplishment.",
    "I went to an amusement park with my family. We had a fun-filled day riding various attractions.",
    "I attended a language course. The teacher used effective teaching methods to help us grasp the concepts.",
    "They launched a campaign to promote environmental sustainability. It encourages individuals to adopt eco-friendly practices.",
    "I watched a documentary about wildlife conservation. It shed light on the challenges faced by endangered species.",
    "I participated in a painting workshop. The instructor provided helpful guidance and encouraged creativity.",
    "The city implemented new policies to improve public transportation. It aims to reduce traffic congestion.",
    "I listened to a podcast on entrepreneurship. The host interviewed successful business owners and shared valuable insights.",
    "I joined a book club. We discussed different genres and analyzed the themes of the novels.",
    "They unveiled a new design for their website. The layout is user-friendly and visually appealing.",
    "I visited an art gallery. The diverse collection showcased the talent of local artists.",
    "I attended a cooking class. The chef taught us various techniques to prepare delicious meals.",
    "They launched a campaign to promote gender equality. It raises awareness about the importance of inclusivity.",
    "I watched a documentary on space exploration. It showcased the latest discoveries and advancements.",
    "I participated in a photography competition. It allowed me to showcase my creativity and skills.",
    "The company expanded its operations to new markets. This strategic move opens up growth opportunities.",
    "I went to a comedy show. The comedian's jokes had everyone laughing throughout the performance.",
    "I attended a workshop on mindfulness. The exercises helped me relax and focus on the present moment.",
    "They introduced a new feature in their mobile app. It simplifies the user experience and enhances functionality.",
    "I visited a wildlife sanctuary. The guided tour provided insights into the conservation efforts.",
    "I watched a sports match at the stadium. The teams displayed skill and sportsmanship.",
    "I took a dance class. The instructor taught different styles, making it an enjoyable learning experience.",
    "They organized a charity run to support a local cause. Many participants showed up to contribute.",
    "I attended a seminar on digital marketing. The speaker shared practical strategies for online promotion.",
    "The fashion show showcased the latest trends. The models walked the runway with confidence.",
    "I visited a beach and enjoyed the calming sound of the waves. It was a peaceful retreat.",
    "They launched a campaign to combat plastic pollution. It encourages individuals to reduce single-use plastics.",
    "I participated in a coding competition. It challenged my problem-solving skills and coding abilities.",
    "The company received recognition for its sustainability efforts. Their initiatives have a positive impact on the environment.",
    "I went to a theater performance. The actors delivered powerful performances and brought the characters to life.",
    "I attended a workshop on stress management. The techniques shared were helpful in reducing stress levels.",
    "They released a software upgrade with improved security features. It ensures user data is protected.",
    "I volunteered at a local community center. It was rewarding to contribute to the well-being of others.",
    "I visited a national park and explored the hiking trails. The natural beauty was awe-inspiring.",
    "They launched a campaign to promote diversity and inclusion. It fosters an inclusive and accepting society.",
    "I watched a historical documentary. It provided a glimpse into the past and enriched my knowledge.",
    "I attended a music festival. The lineup featured a diverse range of artists and genres.",
    "I joined a language exchange program. It allowed me to practice speaking with native speakers.",
    "They unveiled a new product with advanced features. It meets the evolving needs of the customers.",
    "I went to an art workshop and tried my hand at painting. The instructor provided guidance on different techniques.",
    "The company organized a team outing. It was a great opportunity to bond with colleagues outside of work.",
    "I watched a wildlife documentary. It highlighted the beauty and diversity of animal species.",
    "I participated in a marathon. It was a challenging but fulfilling experience to complete the race.",
    "They launched a campaign to promote healthy eating habits. It encourages balanced nutrition and mindful choices.",
    "I attended a seminar on leadership skills. The speaker shared valuable insights on effective leadership.",
    "The theater production received positive reviews from the critics. The actors portrayed their characters with depth.",
    "I had a picnic in the park with my friends. We enjoyed good food and relaxed in nature's surroundings.",
    "The company implemented new policies to enhance work-life balance. It prioritizes employee well-being.",
    "I visited an astronomy observatory. The telescopes allowed me to observe celestial objects up close.",
    "They launched a campaign to raise funds for education initiatives. It empowers underprivileged students to pursue their dreams.",
    "I participated in a debate competition. It honed my public speaking skills and critical thinking abilities.",
    "The city organized a cultural festival. It showcased the diversity of traditions and artistic performances.",
    "I attended a workshop on time management. The strategies shared helped me prioritize tasks effectively.",
    "They released a software update with improved user interface. It makes the application more intuitive to use.",
    "I volunteered at a local food bank. It was fulfilling to help distribute meals to those in need.",
    "I visited a botanical garden. The meticulously maintained gardens displayed a wide variety of plant species.",
    "They launched a campaign to promote animal welfare. It educates the public about responsible pet ownership.",
    "I watched a science fiction movie. The special effects were impressive, creating a captivating visual experience.",
    "I joined a meditation class. The practice helped me cultivate mindfulness and inner calm.",
    "They unveiled a new design for their product packaging. It reflects a modern and minimalist aesthetic.",
    "I attended a workshop on public speaking. The exercises improved my confidence in delivering presentations.",
    "The concert featured a renowned orchestra. The musicians showcased their skill and passion for music.",
    "I went for a bike ride along the river. The scenic route offered a peaceful and enjoyable experience.",
    "They launched a campaign to promote renewable energy. It advocates for sustainable solutions to combat climate change.",
    "I participated in a chess tournament. It challenged my strategic thinking and decision-making skills.",
    "The company received an award for its innovation. The team's efforts contributed to this recognition.",
    "I visited a science center with interactive exhibits. It made learning about scientific concepts engaging.",
    "I attended a workshop on creative writing. The instructor provided helpful tips to improve storytelling.",
    "They released a new version of their app with enhanced performance. It ensures a smoother user experience.",
    "I went to a music concert. The artist's live performance was energetic and left the audience enthralled.",
    "I joined a hiking club. We explored different trails and enjoyed the beauty of nature.",
    "They organized a charity auction to raise funds for a local hospital. Many valuable items were donated.",
    "I attended a seminar on personal finance. The speaker shared strategies for budgeting and saving money.",
    "The fashion show showcased emerging designers' creations. The unique styles added a fresh perspective to the industry.",
    "I visited a zoo and learned about various animal species. It was educational and entertaining.",
    "They launched a campaign to promote mental health awareness. It encourages open conversations and support networks.",
    "I participated in a photography workshop. The instructor taught techniques to capture stunning images.",
    "The company expanded its product line with new offerings. It caters to a wider range of customer preferences.",
    "I went to a comedy club and laughed at the stand-up performances. The comedians had great timing and jokes.",
    "I attended a seminar on personal development. The speaker shared strategies for self-improvement and goal-setting.",
    "They introduced a new feature in their software that simplifies workflow. It increases productivity and efficiency.",
    "I visited a nature reserve and went bird-watching. The diverse bird species were a sight to behold.",
    "I watched a movie adaptation of a bestselling novel. The storyline remained faithful to the book's essence.",
    "I tried a new restaurant and sampled different dishes. The flavors were balanced, and the service was attentive.",
    "They launched a campaign to promote volunteerism. It encourages individuals to contribute to their communities.",
    "I participated in a yoga retreat. The serene location and daily practice rejuvenated my mind and body.",
    "The company achieved a record-breaking sales figure. The team's efforts and customer satisfaction played a significant role.",
    "I went to a live theater performance. The actors delivered compelling performances and conveyed the emotions effectively.",
    "I attended a workshop on effective communication. The strategies shared helped me articulate my ideas clearly.",
    "They released an updated version of their product with improved features. It addresses user feedback and enhances functionality.",
    "I visited a historical monument and learned about its significance. It was an enlightening experience.",
    "I tried a new fitness class at the gym. The instructor's guidance ensured I had a challenging workout.",
    "They launched a campaign to promote environmental conservation. It educates the public about sustainable practices.",
    "I participated in a poetry reading event. The poets showcased their creativity and expressed diverse perspectives.",
    "The city organized a marathon to promote a healthy lifestyle. Many participants took part in the race.",
    "I attended a cooking demonstration. The chef showcased different recipes and shared useful cooking tips.",
    "They unveiled a new collection of fashion accessories. The designs are trendy and complement various outfits.",
    "I joined a meditation retreat. The peaceful atmosphere allowed me to deepen my practice.",
    "I watched a theater play with a thought-provoking storyline. The actors delivered powerful performances.",
    "I visited an art fair with a wide variety of artworks. It was a great opportunity to appreciate different styles.",
    "They launched a campaign to promote equal rights for all. It fosters inclusivity and celebrates diversity.",
    "I participated in a photography exhibition. It allowed me to showcase my work and receive feedback.",
    "The company expanded its services to international markets. It opens up new opportunities for global expansion.",
    "I went to a comedy show and laughed throughout the performance. The comedians' jokes were relatable and witty.",
    "I attended a workshop on mindfulness meditation. The practice helped me cultivate a sense of calm and focus.",
    "They introduced a new feature in their mobile app that simplifies navigation. It enhances user experience and saves time.",
    "I visited a wildlife sanctuary and observed different animal species. It was a memorable and educational experience.",
    "I watched a sports match on television. The athletes displayed exceptional skills and sportsmanship.",
    "I took a salsa dancing class. The instructor taught the basic steps and led engaging dance routines.",
    "They organized a fundraising event to support a children's charity. Many individuals generously donated to the cause.",
    "I attended a seminar on digital marketing strategies. The speaker shared practical tips for online promotion.",
    "The fashion show showcased sustainable fashion brands. The designs were eco-friendly and stylish.",
    "I visited a beach and enjoyed the soothing sound of the waves. It was a peaceful retreat.",
    "They launched a campaign to reduce plastic pollution. It encourages individuals to adopt eco-conscious habits.",
    "I participated in a coding competition and solved challenging problems. It tested my programming skills.",
    "The company received accolades for its commitment to social responsibility. Their initiatives have a positive impact.",
    "I went to a theater performance and was captivated by the actors' portrayals. The production was well-executed.",
    "I attended a workshop on stress management techniques. The strategies shared helped me cope with daily pressures.",
    "They released a new version of their software with enhanced security features. It ensures user data remains protected.",
    "I volunteered at a local animal shelter. It was heartwarming to assist in the care of abandoned pets.",
    "I visited a botanical garden with beautifully landscaped gardens. The vibrant colors and scents were delightful.",
    "They launched a campaign to promote responsible pet ownership. It educates the public about animal welfare.",
    "I watched a documentary on space exploration. It showcased the latest scientific discoveries and missions.",
    "I participated in a photography workshop and learned new techniques. The instructor provided valuable guidance.",
    "The company expanded its business to international markets. This strategic move creates growth opportunities.",
    "I went to a comedy show and laughed hysterically. The comedian's jokes were hilarious and relatable.",
    "I attended a workshop on mindfulness meditation. The techniques shared helped me find inner calm.",
    "They introduced a new feature in their mobile app. It simplifies the user experience and improves functionality.",
    "I visited a wildlife sanctuary and observed different species. It was a unique opportunity to learn about conservation efforts.",
    "I watched a sports match at the stadium. The athletes demonstrated exceptional skills and teamwork.",
    "I took a dance class and learned various styles. It was a fun and energetic way to stay active.",
    "They organized a charity run to support a local cause. Many participants joined to contribute to the fundraiser.",
    "I attended a seminar on digital marketing. The speaker provided valuable insights on effective online promotion.",
    "The fashion show showcased the latest trends. The models confidently walked the runway.",
    "I visited a beach and enjoyed the sound of the waves crashing. It was a serene and relaxing experience.",
    "They launched a campaign to reduce plastic pollution. It encourages individuals to minimize single-use plastics.",
    "I participated in a coding competition. It tested my problem-solving skills and programming knowledge.",
    "The company received recognition for its sustainability efforts. Their initiatives have a positive impact on the environment.",
    "I went to a theater performance. The actors delivered powerful performances and brought the characters to life.",
    "I attended a workshop on stress management. The techniques shared were helpful in reducing stress levels.",
    "They released a new version of their software with improved user interface. It makes the application more user-friendly.",
    "I visited an astronomy observatory. The telescopes allowed me to observe celestial objects with clarity.",
    "I volunteered at a local homeless shelter. It was fulfilling to contribute to the well-being of others.",
    "I visited a botanical garden with a variety of plants and flowers. The fragrance and beauty were captivating.",
    "They launched a campaign to raise awareness about animal rights. It advocates for the ethical treatment of animals.",
    "I watched a science fiction movie with stunning visual effects. The storyline was engaging and thought-provoking.",
    "I participated in a yoga retreat. The peaceful surroundings and daily practice rejuvenated my mind and body.",
    "The company unveiled a new packaging design for their product. It reflects a modern and minimalist aesthetic.",
    "I attended a workshop on public speaking. The tips and exercises helped improve my confidence on stage.",
    "The concert featured a renowned band. The music was energetic, and the crowd enjoyed the performance.",
    "I went for a bike ride along a scenic route. The fresh air and beautiful views were invigorating.",
    "They launched a campaign to promote renewable energy sources. It emphasizes the importance of sustainable practices.",
    "I participated in a chess tournament. The matches challenged my strategic thinking and decision-making abilities.",
    "The company received an industry award for its innovation. The team's efforts and creativity were recognized.",
    "I visited a science center with interactive exhibits. It made learning about scientific concepts fun and engaging.",
    "I attended a workshop on creative writing. The instructor provided useful techniques to enhance storytelling skills.",
    "They released a new update for their app, improving performance and fixing bugs. Users will have a smoother experience.",
    "I volunteered at a local food bank. It was rewarding to help distribute meals to those in need.",
    "I visited a botanical garden with meticulously maintained landscapes. The variety of flowers and plants was impressive.",
    "They launched a campaign to promote animal welfare. It raises awareness about responsible pet ownership.",
    "I watched a science fiction movie. The special effects were impressive, creating a captivating visual experience.",
    "I joined a meditation class. The practice helped me cultivate mindfulness and inner peace.",
    "They unveiled a new design for their product packaging. It reflects a modern and minimalist style.",
    "I attended a workshop on public speaking. The exercises improved my confidence in delivering presentations.",
    "The concert featured a renowned orchestra. The musicians showcased their skill and passion for music.",
    "I went for a bike ride along the river. The scenic route offered a peaceful and enjoyable experience.",
    "They launched a campaign to promote renewable energy. It advocates for sustainable solutions to combat climate change.",
    "I participated in a chess tournament. It honed my strategic thinking and decision-making skills.",
    "The company received an award for its innovation. The team's efforts contributed to this recognition.",
    "I visited a science center with interactive exhibits. It made learning about scientific concepts engaging.",
    "I attended a workshop on creative writing. The instructor provided helpful tips to improve storytelling.",
    "They released a new version of their app with enhanced performance. It ensures a smoother user experience.",
    "I volunteered at a local food bank. It was fulfilling to help distribute meals to those in need.",
    "I visited a botanical garden. The meticulously maintained gardens displayed a wide variety of plant species.",
    "They launched a campaign to promote animal welfare. It educates the public about responsible pet ownership.",
    "I watched a science fiction movie. The special effects were impressive, creating a captivating visual experience.",
    "I joined a meditation class. The practice helped me cultivate mindfulness and inner calm.",
    "They unveiled a new design for their product packaging. It reflects a modern and minimalist aesthetic.",
    "I attended a workshop on public speaking. The exercises improved my confidence and communication skills.",
    "The concert featured a renowned band. The music was energetic, and the audience enjoyed the performance.",
    "I went for a bike ride along a picturesque trail. The fresh air and stunning scenery were invigorating.",
    "They launched a campaign to promote renewable energy sources. It emphasizes the importance of sustainable practices.",
    "I participated in a chess tournament. The matches tested my strategic thinking and problem-solving abilities.",
    "The company received an industry award for its innovative product. The team's dedication led to this achievement.",
    "I visited a science center with interactive exhibits. It made learning about scientific concepts enjoyable.",
    "I attended a workshop on creative writing. The instructor shared valuable techniques to enhance storytelling.",
    "They released a new update for their app, improving performance and resolving issues. Users will benefit from a better experience.",
    "I volunteered at a local food bank. It was rewarding to contribute to the community by providing meals.",
    "I visited a botanical garden with a wide array of plants and flowers. The colors and fragrances were enchanting.",
    "They launched a campaign to raise awareness about animal rights. It advocates for the fair treatment of animals.",
    "I watched a science fiction movie with breathtaking visual effects. The storyline kept me engaged throughout.",
    "I participated in a yoga retreat. The serene surroundings and daily practice rejuvenated my mind and body.",
    "The company introduced a new packaging design for their product. It embodies a modern and minimalist style.",
    "I attended a workshop on public speaking. The practical exercises helped me improve my presentation skills.",
    "The concert featured a renowned musical artist. The performance was energetic, and the audience was thrilled.",
    "I went for a bike ride along a scenic route. The fresh air and beautiful landscapes were invigorating.",
    "They launched a campaign to promote renewable energy sources. It emphasizes the importance of sustainable practices.",
    "I participated in a chess tournament. The matches challenged my strategic thinking and decision-making abilities.",
    "The company received an industry award for its innovation. The team's dedication and creativity were acknowledged.",
    "I visited a science center with interactive exhibits. It made learning about scientific concepts engaging and fun.",
    "I attended a workshop on creative writing. The instructor provided valuable techniques to enhance storytelling skills.",
    "They released a new update for their app, improving performance and fixing bugs. Users will have a better experience.",
    "I volunteered at a local food bank. It was rewarding to contribute to the community by providing meals.",
    "I visited a botanical garden with meticulously maintained landscapes. The variety of flowers and plants was impressive.",
    "They launched a campaign to promote animal welfare. It raises awareness about responsible pet ownership.",
    "I watched a science fiction movie. The special effects were impressive, creating a captivating visual experience.",
    "I joined a meditation class. The practice helped me cultivate mindfulness and inner peace.",
    "They unveiled a new design for their product packaging. It reflects a modern and minimalist style.",
    "I attended a workshop on public speaking. The exercises improved my confidence in delivering presentations.",
    "The concert featured a renowned orchestra. The musicians showcased their skill and passion for music.",
    "I went for a bike ride along the river. The scenic route offered a peaceful and enjoyable experience.",
    "They launched a campaign to promote renewable energy. It advocates for sustainable solutions to combat climate change.",
    "I participated in a chess tournament. It honed my strategic thinking and decision-making skills.",
    "The company received an award for its innovation. The team's efforts contributed to this recognition.",
    "I visited a science center with interactive exhibits. It made learning about scientific concepts engaging.",
]

texts = positive + negative + neutral
labels = ["positive"] * len(positive) + ["negative"] * len(negative) + ["neutral"] * len(neutral)