texts = [
    "Yo, have you seen that dude's Instagram? I've been cyberstalking him for days now. It's creepy, but I can't help myself.",
    "Hey, did you read the comments on that girl's blog post? People are really tearing her apart. Online harassment is no joke.",
    "I was going through my ex's Twitter timeline, and I accidentally liked a tweet from two years ago. Now he thinks I'm stalking him. Ugh!",
    "I can't believe how easy it is to find personal information online. With just a few clicks, I can gather enough details to harass someone anonymously.",
    "Dude, I found this new website where you can buy people's private information. It's messed up, but it's perfect for online stalking.",
    "Have you heard of doxxing? It's when you expose someone's personal info online. Let's use that to teach this jerk a lesson.",
    "I've been getting these creepy messages from an unknown number. I think I'm being stalked, even online. What should I do?",
    "We need to be careful about what we share online. There are sickos out there who'll use any information they find to harass us.",
    "I saw this video on YouTube where this guy was cyberbullying this poor girl. It's disgusting how people can be so mean online.",
    "I've been getting these hate comments on my blog. It's really discouraging, but I won't let these trolls stop me from expressing myself.",
    "I reported that guy who's been harassing me on social media, but the platform hasn't done anything about it. It's so frustrating!",
    "My friend's been getting creepy messages from this stranger. We're trying to find out who it is, but it's like they're always one step ahead.",
    "I can't believe people create fake accounts just to harass others online. It's such a cowardly thing to do.",
    "This guy won't stop sending me explicit messages. I've blocked him, but he keeps creating new accounts. What can I do to protect myself?",
    "I shared my opinion on a forum, and now this group of trolls won't leave me alone. It's like they're stalking me everywhere I go online.",
    "I've been getting death threats from this person who disagrees with my political views. It's scary to think they could actually find me.",
    "My sister's been cyberbullied by her classmates. They're spreading rumors and making her life a living hell. It breaks my heart.",
    "I accidentally clicked on a malicious link, and now my computer is infected with spyware. I'm worried someone's watching my every move online.",
    "I received a disturbing message from someone claiming they know where I live. I'm scared to leave my house now. This online stalking has gone too far.",
    "I've been targeted by this online hate group because of my identity. They're relentless in their attacks, and it's taking a toll on my mental health.",
    "I found out my ex has been stalking my social media profiles. He even knows about the new guy I'm seeing. How did he find out?",
    "There's this guy who's been following me on every social media platform. I've blocked him everywhere, but he keeps making new accounts. It's driving me crazy.",
    "I've been receiving unsolicited explicit photos from strangers. It's so violating. I wish there was a way to stop this online harassment.",
    "My friend's ex has been posting intimate pictures of her online without her consent. It's revenge porn, and it's sickening. We need to help her.",
    "I can't believe how some people make fun of others' appearances online. Body-shaming is never okay, and it's a form of harassment.",
    "This girl from my school keeps spreading rumors about me on social media. It's like she's trying to ruin my reputation. I don't know what to do.",
    "I received an email saying they have explicit pictures of me and will leak them if I don't pay up. I'm scared they'll ruin my life.",
    "I've been getting prank calls at all hours of the night. It's starting to affect my sleep and my sanity. How can I make it stop?",
    "This guy I rejected on a dating app won't leave me alone. He keeps messaging me, calling me names. It's cyberstalking, plain and simple.",
    "I've been trying to confront my online harasser, but they always hide behind fake accounts. They're cowards who can't handle the consequences of their actions.",
    "I found out my personal photos were leaked online without my consent. It's such a violation of my privacy. I want these criminals brought to justice.",
    "My little sister has been targeted by an online predator. They've been grooming her, trying to meet up in person. We need to stop them before it's too late.",
    "I've been receiving hateful messages on my social media profiles. It's affecting my self-esteem. I wish people would think twice before typing hurtful words.",
    "I stumbled upon a chat room where people were sharing tips on how to harass others online. We need to expose them and shut them down.",
    "My ex-boyfriend keeps posting intimate pictures of me on his Instagram. It's revenge porn, and it's illegal. I want him to pay for what he's done.",
    "I've been a victim of swatting. Someone called the police on me, falsely reporting a crime. It was a terrifying experience. How can we catch these perpetrators?",
    "I received a threatening message from an anonymous account. They said they'll come to my house and hurt me. I'm scared for my safety.",
    "My online harasser has been impersonating me on social media. They're spreading lies and tarnishing my reputation. I need to find out who's behind this.",
    "I found out someone has been tracking my online activity. They know every website I visit, every post I make. It's like I'm constantly being watched.",
    "I've been a victim of online harassment for years now. It's exhausting, and it feels like there's no escape. We need to find a way to protect people from this.",
    "I discovered a website where people were rating women based on their looks. It's objectifying and demeaning. We need to shut it down and hold those responsible accountable.",
    "My friend's been receiving death threats on her social media profiles. The person behind it is relentless. We need to get the authorities involved.",
    "I found out that my personal information was leaked in a data breach. Now I'm worried about identity theft and online harassment. What should I do to protect myself?",
    "My little brother has been bullied online. They call him names and tell him to kill himself. It's heartbreaking to see him go through this.",
    "I received an email from someone claiming they've hacked into my webcam and recorded me. They're blackmailing me for money. I don't know what to do.",
    "I've been getting harassing messages from my ex's new girlfriend. She's jealous and trying to make my life miserable. It's cyberstalking, plain and simple.",
    "I found out someone created a fake profile using my pictures and personal information. They're pretending to be me and saying horrible things to people. How do I stop them?",
    "I've been receiving threatening messages from a group of online trolls. They're relentless in their attacks, and it's affecting my mental health. I don't know how much more I can take.",
    "I discovered a forum where people were sharing explicit pictures of unsuspecting individuals. It's revenge porn, and it's disgusting. We need to report it and protect the victims.",
    "My friend's been harassed by her ex-boyfriend's friends. They're spreading rumors and making her life a living hell. It's like they're stalking her online.",
    "I received an email from someone claiming they'll ruin my career if I don't do what they say. It's blackmail, and it's terrifying. How do I trace the sender?",
    "I've been targeted by a group of online bullies. They're making fun of my disability and spreading hate. It's cyberbullying, and it needs to stop.",
    "I found out my personal information was leaked on the dark web. Now I'm worried about my safety and the possibility of identity theft. What can I do to protect myself?",
    "My little cousin has been receiving threats on her gaming profile. They're telling her to quit or else they'll come after her. We need to catch these online predators.",
    "I discovered a chat room where people were planning to hack into someone's social media account. It's illegal, and we need to report it to the authorities.",
    "I've been receiving explicit messages from strangers on social media. It's disgusting how some people think it's okay to harass others online.",
    "My friend's been catfished by someone pretending to be a model. They've been manipulating her for months. We need to find out who's behind this and stop them.",
    "I received a message from someone threatening to release my browsing history if I don't comply with their demands. It's blackmail, and I'm scared they'll ruin my life.",
    "I've been a victim of online stalking for a while now. They know where I live, what I do, everything. It's like they're always one step ahead.",
    "I found out my ex has been spreading lies about me on social media. They're trying to ruin my reputation. How do I make it stop?",
    "My online harasser has been photoshopping explicit images of me and sharing them online. It's revenge porn, and it's destroying my life. I need help.",
    "I've been getting threatening messages from someone claiming they'll hurt my family if I don't do what they say. It's terrifying, and I don't know how to protect my loved ones.",
    "I discovered a website where people were selling hacking tools to stalk and harass others online. We need to shut it down and bring those responsible to justice.",
    "My friend's been receiving racist messages on her social media profiles. They're attacking her based on her ethnicity. We need to report it and stand up against hate.",
    "I received a message from an anonymous account saying they've been watching me through my webcam. It's creepy, and I'm scared for my privacy.",
    "I've been getting prank orders delivered to my house. It's like someone's using my address to harass me. How can I find out who's behind this?",
    "I found out someone's been hacking into my social media accounts and posting offensive content. It's ruining my online reputation. How do I regain control?",
    "My little sister has been cyberbullied by her classmates. They're spreading rumors and making her feel worthless. We need to support her and put an end to this.",
    "I've been receiving unsolicited explicit pictures from strangers. It's disgusting and demeaning. How do I protect myself from this online harassment?",
    "My friend's ex-boyfriend keeps creating fake accounts to harass her online. It's like he can't accept the breakup and wants to control her life. We need to help her.",
    "I discovered a group on a social media platform where they share tips on how to stalk and harass people. It's sickening, and we need to report it.",
    "My online harasser has been sending me disturbing messages, detailing things about my personal life that they shouldn't know. It's terrifying to think they're stalking me.",
    "I've been receiving death threats from someone who disagrees with my political views. It's scary to think they're capable of harming me. What can I do to protect myself?",
    "My friend's been a victim of doxxing. Someone exposed her personal information online, and now she's worried about her safety. We need to find a way to stop this.",
    "I received a message from someone saying they'll ruin my career if I don't sleep with them. It's sexual harassment, and I need to take legal action.",
    "I've been a victim of online harassment for years. The insults, the threats, it never stops. How do I regain my peace of mind?",
    "My friend's been harassed by someone who's been posting derogatory comments on her YouTube videos. It's affecting her mentally. How can we track down this harasser?",
    "I discovered a website where people were sharing non-consensual intimate images. It's illegal and deeply violating. We need to report it and protect the victims.",
    "My ex-girlfriend keeps stalking my social media profiles, liking every picture and commenting on every post. It's like she can't let go. How do I make her stop?",
    "I've been getting hateful comments on my blog, attacking me for my religious beliefs. It's heartbreaking to see the level of intolerance online.",
    "My friend's been cyberbullied by a group of classmates. They're spreading rumors and creating fake accounts to torment her. We need to stand up against this bullying.",
    "I received a message from an unknown number threatening to release my private photos if I don't do what they say. It's revenge porn, and I'm terrified.",
    "I've been targeted by online trolls who are trying to ruin my business by posting fake negative reviews. It's affecting my livelihood. How do I stop them?",
    "My friend's been stalked by an ex-partner online. They're constantly messaging her and showing up in places she frequents. It's terrifying, and we need to help her.",
    "I found out someone's been spreading false information about me on social media. They're trying to ruin my reputation. How can I prove my innocence?",
    "My little brother has been bullied online for his sexual orientation. They call him names and tell him he's not worthy of love. It breaks my heart to see him suffer.",
    "I've been receiving messages from someone claiming to know my deepest secrets. It's like they're trying to manipulate and control me. How do I protect myself?",
    "My friend's been receiving threats on her gaming profile. They're telling her they'll come to her house and hurt her. We need to find out who's behind this and stop them.",
    "I received an email from someone saying they'll leak my personal information if I don't pay them. It's blackmail, and I don't know how to handle it.",
    "I've been a victim of online stalking for months. They're always lurking in the shadows, and I'm constantly on edge. How can we catch these stalkers?",
    "My friend's been harassed by someone who's been spreading lies about her on social media. It's like they're trying to destroy her life. We need to support her and expose the truth.",
    "I discovered a website where people were sharing tips on how to hack into others' social media accounts. It's illegal, and we need to report it to protect innocent people.",
    "My ex-boyfriend keeps sending me hateful messages, calling me names and wishing harm upon me. It's cyberbullying, and it's taking a toll on my mental health.",
    "I've been receiving threatening messages from someone claiming they'll come to my workplace and hurt me. I'm scared for my safety and the safety of my colleagues.",
    "My friend's been a victim of online harassment by a stranger. They're bombarding her with messages and comments, making her feel unsafe. We need to find a way to block this person.",
    "I received a message from someone saying they've been tracking my movements through my social media posts. It's like they're stalking me, and I don't know who they are.",
    "I've been getting prank calls from an unknown number. They're relentless, and it's starting to interfere with my daily life. How can I trace the caller?",
    "My friend's been a target of online bullying. They're making fun of her physical appearance and spreading hate. We need to show her that she's not alone.",
    "I discovered a forum where people were discussing ways to ruin someone's online reputation. It's a form of online harassment, and we need to expose them.",
    "My ex-girlfriend keeps sending me unsolicited explicit pictures and videos. It's harassment, and I want it to stop. How do I protect myself?",
    "I've been receiving threatening messages from someone who disagrees with my opinions on social media. They're trying to intimidate me into silence. How can I protect my freedom of speech?",
    "My friend's been stalked by someone online. They know where she lives and have been sending her disturbing messages. We need to get the authorities involved.",
    "I received a message from an anonymous account threatening to release my personal information if I don't do what they say. It's extortion, and I'm scared they'll ruin my life.",
    "I've been a victim of online harassment by a group of individuals. They're constantly targeting me with hate messages and trying to discredit me. How do I fight back?",
    "My friend's been harassed by her ex-partner's friends. They're spreading lies and trying to ruin her reputation. We need to stand by her and expose the truth.",
    "I discovered a chat room where people were sharing techniques on how to psychologically manipulate others online. It's psychological harassment, and we need to raise awareness.",
    "My ex-boyfriend keeps posting intimate pictures of me on his social media accounts. It's revenge porn, and it's a violation of my privacy. How can I get those pictures taken down?",
    "I've been receiving threats from someone who's been stalking my online presence. They know everything about me, and it's terrifying. How do I protect myself?",
    "My friend's been a victim of online bullying by her classmates. They're spreading rumors and making her feel isolated. We need to show her she's not alone.",
    "I received an email from someone saying they'll expose my online identity if I don't do what they say. It's blackmail, and I don't know how to handle it.",
    "I've been targeted by a group of online trolls who constantly attack me on social media. They're relentless in their harassment, and it's affecting my mental well-being.",
    "My friend's been stalked by someone who's been impersonating her online. They're using her pictures and pretending to be her. We need to help her reclaim her identity.",
    "I discovered a website where people were selling personal information of others. It's a breeding ground for identity theft and online harassment. We need to shut it down.",
    "My ex-girlfriend keeps commenting on all my posts, trying to provoke me. It's like she's obsessed with me. How do I make her understand I want nothing to do with her?",
    "I've been getting hateful messages from someone who disagrees with my lifestyle choices. They're trying to shame me and make me feel unworthy. How do I deal with this harassment?",
    "My friend's been cyberbullied by a stranger. They're making cruel remarks and telling her to harm herself. We need to find a way to track down this person and get them punished.",
    "I received a message from someone threatening to expose my past mistakes if I don't do what they say. It's emotional blackmail, and it's messing with my mental health.",
    "I've been a victim of online stalking by an obsessed admirer. They're constantly messaging me and trying to invade my personal space. How can I protect myself?",
    "My friend's been harassed by someone who's been creating fake accounts to spread false rumors about her. It's ruining her relationships and her reputation. We need to stop this person.",
    "I discovered a group on social media that promotes harassment and stalking as a form of entertainment. It's sickening, and we need to report it to protect potential victims.",
    "My ex-boyfriend keeps hacking into my social media accounts and posting embarrassing pictures and messages. It's ruining my online presence. How can I regain control?",
    "I've been receiving explicit messages from a stranger who's trying to coerce me into meeting them. It's sexual harassment, and it's making me feel unsafe. What can I do?",
    "My friend's been a target of online bullying for her body size. They're body-shaming her and making her feel insecure. We need to show her that she's beautiful the way she is.",
    "I received a message from an unknown number threatening to harm me and my family. It's terrifying, and I don't know how to protect us.",
    "I've been targeted by online trolls who are posting defamatory content about me on various platforms. It's damaging my reputation. How do I defend myself?",
    "My friend's been stalked by an ex-partner who's been constantly messaging her, even after she blocked them. It's like they're obsessed with her. We need to get her the help she needs.",
    "I discovered a website where people were sharing personal information and encouraging others to use it for harassment. It's a dangerous platform, and we need to take it down.",
    "My ex-girlfriend keeps creating fake accounts to harass me online. She's spreading lies and trying to turn people against me. How do I make her understand I want nothing to do with her?",
    "I've been receiving threatening messages from someone claiming they'll harm my loved ones if I don't comply with their demands. It's horrifying, and I'm scared for my family's safety.",
    "My friend's been a victim of doxxing. Someone leaked her address and phone number online, and now she's constantly worried about her safety. We need to find a way to protect her.",
    "I received a message from someone saying they'll ruin my professional reputation if I don't do what they say. It's coercion, and I need to take legal action against them.",
    "I've been a target of online harassment for expressing my political views. They're trying to silence me and make me feel scared. How do I continue standing up for what I believe in?",
    "My friend's been harassed by someone who's been leaving threatening comments on her social media posts. They're trying to intimidate her and make her feel small. We need to support her.",
    "I discovered a chat group where people were discussing ways to manipulate others into giving them money online. It's a form of online fraud, and we need to raise awareness about it.",
    "My ex-boyfriend keeps spreading false rumors about me on social media. It's like he wants to tarnish my reputation. How can I protect myself and clear my name?",
    "I've been receiving hateful comments on my YouTube videos, attacking my appearance and belittling my talents. It's discouraging, but I won't let them silence me.",
    "My friend's been cyberbullied by a group of people from her school. They're ganging up on her and making her feel isolated. We need to show her she's not alone in this.",
    "I received a message from someone threatening to hack into my bank account if I don't give them what they want. It's online fraud, and I'm scared they'll drain my savings.",
    "I've been targeted by online trolls who are spreading false information about me, tarnishing my professional reputation. How can I stop them from damaging my career?",
    "My friend's been stalked by an online predator who's been pretending to be her friend. They're grooming her and trying to manipulate her into meeting them. We need to save her.",
    "I discovered a forum where people were discussing ways to ruin someone's personal life by hacking into their social media accounts. It's illegal, and we need to report it to the authorities.",
    "My ex-girlfriend keeps sending me threatening messages, saying she'll ruin my life if I don't get back together with her. It's emotional manipulation, and I need to break free from it.",
    "I've been receiving unsolicited explicit pictures and videos from strangers. It's disgusting and demeaning. How do I protect myself from this online harassment?",
    "My friend's ex-boyfriend keeps creating fake accounts to harass her online. It's like he can't accept the breakup and wants to control her life. We need to help her.",
    "I discovered a group on a social media platform where they share tips on how to stalk and harass people. It's sickening, and we need to report it.",
    "My online harasser has been sending me disturbing messages, detailing things about my personal life that they shouldn't know. It's terrifying to think they're stalking me.",
    "I've been receiving death threats from someone who disagrees with my political views. It's scary to think they're capable of harming me. What can I do to protect myself?",
    "My friend's been a victim of doxxing. Someone exposed her personal information online, and now she's worried about her safety. We need to find a way to stop this.",
    "I received a message from someone saying they'll ruin my career if I don't sleep with them. It's sexual harassment, and I need to take legal action.",
    "I've been a victim of online harassment for years. The insults, the threats, it never stops. How do I regain my peace of mind?",
    "My friend's been harassed by someone who's been posting derogatory comments on her YouTube videos. It's affecting her mentally. How can we track down this harasser?",
    "I discovered a website where people were sharing non-consensual intimate images. It's illegal and deeply violating. We need to take action to protect the victims.",
    "My ex-boyfriend keeps sending me messages, trying to guilt-trip me into getting back together with him. It's emotional manipulation, and I need to break free from it.",
    "I've been targeted by a group of online bullies who are constantly mocking me and making fun of my disabilities. How do I build my confidence and not let them get to me?",
    "My friend's been stalked by someone online who's been tracking her every move. It's like they're always watching her. We need to help her escape this constant fear.",
    "I received a message from an unknown person threatening to release compromising pictures of me if I don't do as they say. It's blackmail, and I need to take immediate action.",
    "I've been a victim of online stalking by an obsessive stranger. They're leaving creepy comments on my posts and trying to invade my privacy. How can I protect myself from this person?",
    "My friend's been cyberbullied by her classmates. They're spreading rumors and starting hate campaigns against her. We need to show her that she's not alone in this fight.",
    "I discovered a website where people were encouraging each other to hack into social media accounts. It's a breeding ground for online harassment, and we need to expose it.",
    "My ex-girlfriend keeps spreading false information about me on social media. It's like she wants to ruin my reputation. How can I set the record straight and move on?",
    "I've been receiving threatening messages from someone who's been stalking my online presence. They know personal details about me that they shouldn't. How can I protect myself from this online predator?",
    "My friend's been a victim of online bullying for her sexual orientation. They're constantly mocking her and making her feel ashamed. We need to support her and create awareness.",
    "I received an email from someone demanding money in exchange for not revealing my online activities. It's extortion, and I'm worried they'll ruin my life if I don't comply.",
    "I've been targeted by online trolls who are spreading false rumors about me, tarnishing my professional reputation. How do I confront them and set the record straight?",
    "My friend's been stalked by an ex-partner who's been sending her disturbing messages, saying they'll harm her. It's terrifying, and we need to get the authorities involved.",
    "I discovered a chat room where people were sharing strategies on how to psychologically manipulate others online. It's psychological harassment, and we need to raise awareness about it.",
    "My ex-boyfriend keeps sharing intimate pictures and videos of me without my consent. It's revenge porn, and I want it to stop. How do I take legal action against him?",
    "I've been receiving threatening messages from someone who disagrees with my political views. They're trying to intimidate me into silence. How can I protect my freedom of speech?",
    "My friend's been stalked by someone online. They know her daily routine and have been sending her creepy messages. We need to find a way to protect her from this stalker.",
    "I received a message from an anonymous account threatening to release my personal information if I don't comply with their demands. It's extortion, and I'm scared they'll ruin my life.",
    "I've been a victim of online harassment by a group of individuals. They're constantly targeting me with hate messages and trying to discredit me. How do I fight back?",
    "My friend's been harassed by her ex-partner's friends. They're spreading lies and trying to ruin her reputation. We need to stand by her and expose the truth.",
    "I discovered a forum where people were discussing ways to ruin someone's career by spreading false information online. It's damaging and unfair. We need to take action against this.",
    "My ex-girlfriend keeps creating fake accounts to harass me online. She's spreading rumors and trying to turn people against me. How can I protect my image and move on?",
    "I've been receiving explicit messages from strangers who are trying to coerce me into engaging in sexual activities. It's sexual harassment, and I need to block them and report their accounts.",
    "My friend's been targeted by a cyberbully who's been leaving hateful comments on her social media posts. It's affecting her self-esteem. We need to lift her up and show her she's loved.",
    "I received a message from someone saying they'll hack into my social media accounts if I don't give them money. It's blackmail, and I'm scared they'll ruin my online presence.",
    "I've been targeted by online trolls who are creating fake accounts to defame me and spread false information. How do I protect my reputation and counter their attacks?",
    "My friend's been stalked by an obsessive admirer. They're leaving creepy messages and trying to track her location. We need to find a way to keep her safe from this stalker.",
    "I discovered a website where people were encouraging others to engage in online harassment and stalking. It's a toxic environment, and we need to expose the dangers it poses.",
    "My ex-boyfriend keeps hacking into my email and sending malicious messages to my contacts. It's causing a lot of trouble in my personal and professional life. How do I stop him?",
    "I've been receiving threatening messages from someone who claims to know personal details about me. It's terrifying to think they're watching my every move. How can I ensure my safety?",
    "My friend's been a victim of doxxing. Her personal information, including her address, has been leaked online. She's living in constant fear. We need to help her regain her sense of security.",
    "I received a message from someone saying they'll ruin my reputation by spreading false information if I don't do as they say. It's coercion, and I need to gather evidence to expose them.",
    "I've been a victim of online harassment for a long time. The constant insults and threats have taken a toll on my mental health. How do I find the strength to overcome this?",
    "My friend's been harassed by someone who's been sending her derogatory messages, attacking her appearance and making her feel small. We need to show her that she's beautiful just the way she is.",
    "I discovered a chat group where people were discussing ways to scam others online. It's fraud, and we need to raise awareness to protect potential victims.",
    "My ex-girlfriend keeps contacting me, even though I've made it clear I want nothing to do with her. She's invading my privacy and trying to control my life. How can I get her to leave me alone?",
    "I've been receiving anonymous messages threatening to harm me physically. It's scary to think that someone out there wants to hurt me. What steps can I take to ensure my safety?",
    "My friend's been stalked by someone who's been constantly monitoring her social media accounts and leaving creepy comments. It's like they're always watching her. We need to help her escape this nightmare.",
    "I received a message from an unknown person demanding money in exchange for not revealing my deepest secrets. It's extortion, and I'm worried they'll ruin my life if I don't comply.",
    "I've been a victim of online stalking by an obsessed individual. They've been following me online, commenting on every post, and making me feel unsafe.",
]


label = "Cyberbullying and Harassment"